import { useState, useEffect, useCallback, useRef } from "react";

const Q = [
// ========== DOMAIN 1: PM FUNDAMENTALS & CORE CONCEPTS (50 Qs, ~36%) ==========
{q:"A critical vendor goes bankrupt mid-project. The PM has identified alternatives but switching adds 3 weeks and $40K. What should the PM do FIRST?",a:["Check the risk register for a pre-planned response to vendor failure","Begin transitioning to the best alternative vendor immediately to minimize delay","Submit a change request with schedule and cost impact for sponsor review","Request sponsor guidance on whether to continue or terminate"],c:0,e:"A risk event materialized. First action: check if you planned for this. The risk register should have vendor failure as an identified risk with a response strategy. Option A (change request) is the likely NEXT step after checking plans. Option B skips approval. Option D is premature before checking your own plans. On the exam: risk occurs → check risk register → invoke planned response → assess impact → change request → approval → execute."},
{q:"The charter is approved but a key department head was excluded and now opposes the project. What should the PM do?",a:["Proceed since the charter has executive backing","Request the sponsor override the department head","Revise the charter to incorporate their requirements immediately","Meet with the department head to understand their concerns before proceeding"],c:3,e:"When a stakeholder opposes you, listen first. The department head has legitimate concerns from being excluded. Meeting them addresses the root cause. Proceeding (A) creates an active opponent. Escalating (B) is adversarial. Revising the charter (D) may happen later but understanding concerns comes first. On the exam, opposition → listen and understand → then act."},
{q:"A team member says a vendor might not deliver on time. Another says the vendor has always been reliable. How should the PM categorize these?",a:["The first raises an issue; the second makes an assumption","The first identifies a risk; the second makes an assumption","The first documents a constraint; the second identifies an opportunity","The first makes an assumption; the second identifies a risk"],c:1,e:"First team member: RISK (uncertain future event). It hasn't happened, so not an issue. Second: ASSUMPTION (treating something as true without proof). Risk = future uncertainty. Issue = current problem. Assumption = believed true without proof. Constraint = known limitation. These four are tested together constantly."},
{q:"A high-performer becomes disengaged after being passed over for promotion. Per Maslow's hierarchy, which need is unmet?",a:["Safety, because their position feels threatened","Self-actualization, because they can't reach their potential","Belonging, because they feel excluded from advancement opportunities","Esteem, because recognition and achievement needs are unmet"],c:3,e:"Being passed over directly impacts esteem (recognition, respect, achievement). They performed well before (lower needs met). Safety (A) = job security. Belonging (C) = team relationships. Self-actualization (D) requires esteem to be met first. Apply motivation theories to the scenario, don't just recite definitions."},
{q:"The PM has limited authority and must negotiate for resources. Team members report to functional managers. What organization type is this?",a:["Functional organization","Weak matrix organization","Balanced matrix organization","Projectized organization"],c:1,e:"PM exists but has limited authority, must negotiate = weak matrix. Functional = PM has almost no authority. Balanced = shared authority. Projectized = PM has full authority. The degree of PM authority tells you the structure."},
{q:"The sponsor demands execution start immediately. The charter exists but no project management plan. What should the PM do?",a:["Explain that a project management plan must be developed before execution begins","Start work on well-understood deliverables while developing the plan","Create a high-level plan and start execution simultaneously","Have the team begin based on the charter's scope description"],c:0,e:"Without a plan: no baselines, no quality standards, no risk management, no communication strategy. You can't measure progress or control changes. The charter authorizes the project but doesn't define HOW. On the exam, when pressured to skip planning, push back professionally."},
{q:"During closure, the PM finds lessons learned were never collected. What is the BIGGEST problem?",a:["The closure report will be incomplete","The PMO will reject the documentation","The sponsor won't approve closure","Team members have dispersed and their insights are permanently lost"],c:3,e:"The real damage is lost institutional knowledge for future projects. Team members who experienced problems and found solutions are gone. Reports (A) and approvals (C, D) are secondary. This is why PMI emphasizes continuous lessons learned, not just at project end."},
{q:"Project A has NPV of $500K. Project B has NPV of $350K. Similar resources required. Which should the PM recommend?",a:["Project B for lower risk exposure","Either, since NPV alone is insufficient","Project A for greater expected return on investment","Project B for likely shorter payback period"],c:2,e:"Higher NPV = more value created. NPV already accounts for time value of money. The question states similar resources, removing that variable. NPV says nothing about payback period (D). On the exam: higher NPV = better. Shorter payback = better. Higher IRR = better."},
{q:"A company invests in developer training and code reviews. In cost of quality terms, this is:",a:["Prevention costs, aiming to stop defects before they occur","Appraisal costs, evaluating work quality","Internal failure costs, catching problems before delivery","External failure costs, preventing customer complaints"],c:0,e:"Prevention = investments to stop defects (training, process improvement). Appraisal = detecting defects (testing, inspections). Internal failure = fixing before delivery (rework). External failure = fixing after delivery (warranty, lawsuits). Training and reviews stop defects at the source = prevention."},
{q:"'The system must handle 10,000 concurrent users with sub-2-second response time.' This is a:",a:["Functional requirement","Business requirement","Constraint","Non-functional requirement"],c:3,e:"Performance criteria (capacity, speed) = non-functional requirements describing HOW the system performs. Functional = WHAT it does ('process refunds'). Business = organizational needs ('improve satisfaction 20%'). Constraint = project limitation (budget, deadline). Non-functional includes: performance, security, reliability, scalability, usability."},
{q:"During brainstorming, a team member criticizes another's idea immediately. The PM should:",a:["Allow it since filtering weak ideas early saves time","Ask the critic to present their own solution instead","End the session and switch to Delphi technique","Remind the team that all ideas are captured without judgment first, then evaluated"],c:3,e:"Brainstorming's core rule: no criticism during generation. Evaluation comes after. The PM as facilitator protects the process. Allowing criticism (A) kills creativity. Ending (C) gives up too easily. Redirecting (B) doesn't fix the process violation."},
{q:"The team is establishing ground rules, developing trust, and working through disagreements constructively. This is Tuckman's:",a:["Forming stage","Storming stage","Norming stage","Performing stage"],c:2,e:"'Establishing ground rules and working through disagreements constructively' = norming. Forming = polite, cautious. Storming = raw, unresolved conflict. Norming = building working agreements. Performing = cohesive, productive. Storming vs. norming: storming = active clashing. Norming = resolving and building norms."},
{q:"A team member inflates time estimates to create personal buffer. This primarily violates which PMI value?",a:["Responsibility","Fairness","Respect","Honesty"],c:3,e:"The core act is providing false data = dishonesty. While it touches responsibility and fairness, the PRIMARY violation is honesty. PMI's four values: Responsibility, Respect, Fairness, Honesty. On the exam, identify the primary value by looking at the core action."},
{q:"Work performance data → work performance information → work performance reports. What is the correct description of this progression?",a:["Reports come first, then get analyzed into information, then reduced to data","Raw data is collected during execution, analyzed into contextualized information, then compiled into stakeholder reports","Information is gathered first, transformed into data, then summarized","Data and information are identical; reports summarize both"],c:1,e:"Data = raw observations ('35% complete'). Information = analyzed data ('10% behind schedule'). Reports = formatted for stakeholders ('status report with corrective actions'). Each level serves different audiences. The PM transforms data through analysis, then packages for decision-makers."},
{q:"The project management plan differs from project documents in that:",a:["The plan contains subsidiary plans and baselines; project documents like the risk register support but aren't part of the formal plan","There is no meaningful difference","Project documents are only created during execution","The plan only includes schedule and budget"],c:0,e:"The PM plan contains subsidiary plans (scope mgmt plan, schedule mgmt plan, etc.) and baselines (scope, schedule, cost). Project documents are separate: risk register, stakeholder register, issue log, lessons learned, change log. They support but aren't part of the plan. This distinction appears frequently on the exam."},
{q:"A functional manager refuses to release a resource the PM needs. They have equal authority. What should the PM do FIRST?",a:["Escalate to the sponsor with schedule impact documentation","Accept partial availability and adjust the schedule","Negotiate to understand their constraints and explore compromises","Hire a contractor to avoid the conflict"],c:2,e:"Equal authority = balanced matrix. Neither can overrule the other. Escalating (A) skips negotiation and damages the relationship. Accepting (B) fails the project without trying. Contractors (D) add cost and avoid the conversation. Negotiate first, escalate with data if it fails."},
{q:"A project requires strict regulatory compliance with complete documentation and phase-gate approvals before proceeding. Which approach?",a:["Predictive with phase-gate reviews","Hybrid with agile development and predictive compliance","Adaptive with sprint documentation","Iterative with regulatory checkpoints"],c:0,e:"'Complete before proceeding' + 'regulatory compliance' + 'full documentation' = predictive with gates. Adaptive (A) doesn't naturally produce sequential documentation trails. Hybrid (B) could work but the question requires completion before advancing. Iterative (D) revisits work, conflicting with sequential approval."},
{q:"The PM is comparing the sponsor and PM roles. Which is CORRECT?",a:["The sponsor manages day-to-day activities","The PM achieves project objectives; the sponsor provides funding and resolves issues beyond PM authority","They share equal responsibility for all decisions","The PM reports to the sponsor only during initiation"],c:1,e:"PM = tactical execution. Sponsor = strategic support and organizational authority. The sponsor doesn't manage daily activities (A), doesn't share all decisions equally (C), and the relationship continues throughout (D)."},
{q:"Budget fixed at $500K is a ___. Belief that regulations won't change is a ___.",a:["Assumption; constraint","Constraint; assumption","Risk; constraint","Assumption; risk"],c:1,e:"Fixed budget = known limitation = constraint. Believing regulations won't change = treating uncertain future as certain = assumption. Constraints are KNOWN. Assumptions are BELIEVED. If the assumption proves wrong, it becomes a risk event."},
{q:"A project team has 8 members. One member leaves. How many communication channels are lost?",a:["7","8","28","21"],c:0,e:"Original channels: 8(7)/2 = 28. New channels: 7(6)/2 = 21. Lost: 28 - 21 = 7 channels. Each person removed eliminates (N-1) channels where N is the original count. 8-1 = 7 lost channels. Formula: N(N-1)/2."},
{q:"A PM uses a fishbone diagram during a quality review. This tool is BEST used for:",a:["Scheduling activities in sequence","Identifying root causes of a problem by categorizing potential causes","Tracking project costs against budget","Prioritizing stakeholder engagement"],c:1,e:"Fishbone (Ishikawa/cause-and-effect) diagrams map potential causes of a problem into categories (people, process, equipment, materials, environment, management). They help identify ROOT causes rather than symptoms. Not for scheduling (A), cost tracking (C), or stakeholder management (D)."},
{q:"The PM discovers the project's communications are ineffective. Multiple stakeholders say they aren't getting the information they need. What should the PM review FIRST?",a:["The communications management plan to verify it addresses stakeholder needs","The project charter for stakeholder identification","The risk register for communication-related risks","The project schedule for upcoming deliverable dates"],c:0,e:"The communications management plan defines who gets what information, how, and when. If communications are failing, the plan either doesn't address stakeholder needs or isn't being followed. The charter (A) identifies stakeholders but doesn't define communications. Risk register (C) and schedule (D) don't address the root communication problem."},
{q:"A PM is asked to select a project using the payback period method. Project X pays back in 18 months. Project Y pays back in 24 months. Both have similar NPV. Which is preferred?",a:["Project X because shorter payback period means faster return on investment","Project Y because longer payback means higher total return","Either, since payback period is unreliable without NPV","Cannot determine without knowing the IRR"],c:0,e:"Shorter payback = faster return = less time exposed to risk. With similar NPV, the shorter payback is preferred. Longer payback (A) doesn't mean higher return. Payback period is a valid selection criterion (C), though limited. IRR (D) is another tool but isn't required here."},
{q:"A change request can include all of the following EXCEPT:",a:["Corrective action to get the project back on track","Preventive action to keep the project on track","Defect repair to fix a broken component","Risk identification to document new uncertain events"],c:3,e:"Change requests encompass corrective actions (fix deviation), preventive actions (prevent deviation), and defect repairs (fix broken deliverables). Risk identification (D) is a separate process that adds risks to the risk register, not a type of change request. On the exam, know the three types of changes that flow through change control."},
// ========== DOMAIN 2: PREDICTIVE/PLAN-BASED (24 Qs, ~17%) ==========
{q:"BAC=$200K. Project is 50% complete, spent $120K. What is the CPI?",a:["0.83","1.20","0.50","1.00"],c:0,e:"EV = 50% × $200K = $100K. CPI = EV/AC = $100K/$120K = 0.83. For every dollar spent, 83 cents of value. CPI < 1 = over budget. Don't confuse % complete with CPI."},
{q:"BAC=$500K. Should be 40% done, actually 30% done. Spent $180K. What is the SPI?",a:["0.67","0.83","0.75","1.33"],c:2,e:"EV = 30% × $500K = $150K. PV = 40% × $500K = $200K. SPI = EV/PV = $150K/$200K = 0.75. AC ($180K) is NOT used for SPI. The exam gives extra numbers to see if you grab the wrong one. SPI uses EV and PV only."},
{q:"EV=$90K, PV=$100K, AC=$95K. What are CV and SV?",a:["CV=-$5K, SV=-$10K","CV=$5K, SV=-$10K","CV=-$5K, SV=$10K","CV=$5K, SV=$10K"],c:0,e:"CV = EV-AC = $90K-$95K = -$5K (over budget). SV = EV-PV = $90K-$100K = -$10K (behind schedule). Both negative = both problems. Both formulas start with EV. Negative = bad."},
{q:"BAC=$300K, CPI=0.75. What is the EAC?",a:["$400,000","$225,000","$375,000","$300,000"],c:0,e:"EAC = BAC/CPI = $300K/0.75 = $400K. Project will cost $100K more than budgeted. When CPI < 1, EAC > BAC. When CPI > 1, EAC < BAC. EAC answers: 'What will this project cost total?'"},
{q:"BAC=$600K. At halfway: EV=$270K, AC=$300K. Sponsor asks if the project should continue. Which metric BEST answers this?",a:["CPI showing current cost efficiency","SPI showing schedule performance","TCPI showing efficiency needed to finish on budget","EAC forecasting total project cost if current performance continues"],c:3,e:"The sponsor asks a forward-looking question: should we continue? EAC (C) directly answers: 'total cost will be $666,667 if this continues.' CPI (A) is a snapshot, not a forecast. SPI (B) addresses schedule, not the budget question. TCPI (D) shows what's needed but doesn't forecast total cost."},
{q:"BAC=$800K, EV=$500K, AC=$600K. What is the TCPI?",a:["1.50","1.00","0.83","1.20"],c:0,e:"TCPI = (BAC-EV)/(BAC-AC) = ($800K-$500K)/($800K-$600K) = $300K/$200K = 1.50. Team needs $1.50 per dollar on remaining work. Current CPI = 0.83. Going from 0.83 to 1.50 is essentially impossible. Time for a budget conversation with the sponsor."},
{q:"BAC=$1M. 60% complete, spent $700K. What is the VAC?",a:["-$166,667","+$166,667","-$300,000","+$300,000"],c:0,e:"EV = 60% × $1M = $600K. CPI = $600K/$700K = 0.857. EAC = $1M/0.857 = $1,166,667. VAC = BAC-EAC = $1M-$1,166,667 = -$166,667. Project will be ~$167K over budget. Full chain: % → EV → CPI → EAC → VAC."},
{q:"EAC=$450K, AC=$180K. What is the ETC?",a:["$270,000","$630,000","$450,000","$180,000"],c:0,e:"ETC = EAC-AC = $450K-$180K = $270K. ETC = how much MORE money to finish. Simple subtraction but the exam tests whether you know which formula to apply."},
{q:"CPI=0.93, SPI=1.1. What is most likely happening?",a:["Fast tracking","Resource leveling","The project is behind with no corrective action","Crashing"],c:3,e:"Ahead of schedule (SPI>1) + over budget (CPI<1) = classic crashing signature. Paying extra to compress the timeline. Fast tracking (A) overlaps activities without adding cost. Resource leveling (B) typically extends schedule."},
{q:"O=6, M=10, P=20 days. What is the PERT estimate?",a:["12 days (simple average)","14 days","10 days (most likely only)","11 days (PERT weighted)"],c:3,e:"PERT = (6 + 40 + 20)/6 = 66/6 = 11 days. Simple average = (6+10+20)/3 = 12 (option A), a common trap. PERT weights most likely 4x. Know both: PERT = (O+4M+P)/6. Triangular = (O+M+P)/3."},
{q:"O=10, M=15, P=26. What are the PERT estimate and standard deviation?",a:["PERT=16, SD=2.67","PERT=17, SD=4","PERT=15, SD=2.67","PERT=16, SD=8"],c:0,e:"PERT = (10+60+26)/6 = 96/6 = 16. SD = (P-O)/6 = (26-10)/6 = 2.67. At 95% confidence (±2 SD): 16 ± 5.34 = 10.66 to 21.34 days. SD formula: (Pessimistic - Optimistic) / 6."},
{q:"Three paths: P1: A(3)→B(5)→C(2)=10. P2: A(3)→D(4)→E(6)=13. P3: A(3)→F(3)→G(3)=9. What is the critical path?",a:["Path 1 (10 days)","Path 3 (9 days)","Path 2 (13 days)","All paths are critical"],c:2,e:"Critical path = longest path = Path 2 at 13 days. It determines minimum project duration. Path 1 has 3 days float. Path 3 has 4 days float. Critical path activities (A,D,E) have zero float."},
{q:"Activity D on the critical path (from above) is delayed 2 days. What happens?",a:["No impact, other paths absorb it","Project delayed 1 day","Project delayed 2 days","Path 1 becomes the critical path"],c:2,e:"D is on the critical path with zero float. Any delay = equal project delay. 2-day delay to D = 2-day project delay. Path 2 becomes 15 days. Path 1 (10) and Path 3 (9) still have float."},
{q:"Activity B (Path 1, not critical) is delayed 4 days. What happens?",a:["No impact","Project delayed 4 days","Project delayed 3 days","Path 1 becomes critical at 14 days, delaying the project 1 day"],c:3,e:"Path 1 has 3 days float (13-10). A 4-day delay exceeds float by 1. Path 1 becomes 14 days, now longest (exceeding original CP of 13). Project delayed 1 day. Non-critical activities CAN become critical if delays exceed their float."},
{q:"Activity X: ES=1, EF=5, LS=3, LF=7. What is the total float?",a:["0 days","5 days","7 days","2 days"],c:3,e:"Float = LS-ES = 3-1 = 2. (Or LF-EF = 7-5 = 2.) Can slip 2 days without delaying project. Float > 0 = NOT on critical path. Float = 0 = critical path."},
{q:"Activity A (5 days) finishes, then a mandatory 2-day lag, then Activity B (3 days), then Activity C (4 days). Total duration?",a:["14 days","12 days","10 days","16 days"],c:0,e:"A(5) + lag(2) + B(3) + C(4) = 14. Lag adds real calendar time. If this were a 2-day LEAD, B would start 2 days before A finishes, saving time. Lead compresses; lag extends."},
{q:"The team can't decompose a work package because the technology hasn't been selected. They'll do it in 3 months. This is:",a:["Progressive elaboration","Scope creep","Rolling wave planning","Fast tracking"],c:2,e:"Rolling wave = deliberate strategy of detailed near-term planning with high-level future planning. Progressive elaboration (A) = general concept that details evolve. Rolling wave is a specific TECHNIQUE. Scope creep (B) = uncontrolled changes."},
{q:"Adding a second team to compress a critical path activity at extra cost is ___. Starting a successor before the predecessor finishes is ___.",a:["Crashing; fast tracking","Both crashing","Fast tracking; crashing","Resource leveling; lead time"],c:0,e:"More resources + more cost to compress = crashing. Overlapping sequential activities = fast tracking. Crashing costs money. Fast tracking increases risk. Both only work on critical path activities."},
{q:"A PM compares contracts. Scope is poorly defined and will evolve. Needs flexibility with cost protection. Best contract?",a:["Firm Fixed Price","Cost Plus Fixed Fee","Time and Materials with not-to-exceed clause","Fixed Price Incentive Fee"],c:2,e:"Undefined evolving scope + cost protection = T&M with cap. Fixed price (A,D) forces expensive renegotiations. Pure cost-plus (B) has no ceiling. The not-to-exceed clause provides the cost protection."},
{q:"BAC=$400K, project 50% complete, spent $220K. The sponsor asks: 'Can we finish on budget?' What is the TCPI?",a:["0.90","0.83","1.03","1.11"],c:3,e:"EV = 50% × $400K = $200K. TCPI = (BAC-EV)/(BAC-AC) = ($400K-$200K)/($400K-$220K) = $200K/$180K = 1.11. Need $1.11 per dollar going forward. Current CPI = $200K/$220K = 0.91. Going from 0.91 to 1.11 is a significant improvement. Challenging but potentially feasible."},
{q:"A project has CPI=1.25 and BAC=$500K. What will the project cost?",a:["$400,000","$500,000","$625,000","$375,000"],c:0,e:"EAC = BAC/CPI = $500K/1.25 = $400K. CPI > 1 = UNDER budget. Project will cost LESS than planned. Not all EAC problems are overruns. This is a good situation."},
{q:"At project completion, EV must equal:",a:["AC","PV","It varies depending on performance","BAC"],c:3,e:"100% complete means EV = 100% × BAC = BAC. At completion: EV = PV = BAC. But AC may differ (spent more or less than budgeted). CPI at completion = BAC/AC."},
{q:"Each server takes 4 hours to configure. 50 servers. Two technicians work 8-hour days. How many days?",a:["25 days","50 days","12.5 days","100 days"],c:2,e:"Total work = 50 × 4 = 200 hours. Capacity = 2 × 8 = 16 hours/day. Duration = 200/16 = 12.5 days. Parametric estimating: parameter × quantity ÷ capacity. Watch for the trap of forgetting multiple resources."},
// ========== DOMAIN 3: AGILE FRAMEWORKS (28 Qs, ~20%) ==========
{q:"Sprint planning: team says 30 points based on velocity. PO insists on 45 for a deadline. SM should:",a:["Support the PO since deadlines take priority","Tell the PO 45 is impossible based on data","Let them negotiate without interference","Help the team voice concerns, present velocity data, and facilitate discussion about which 30 points best serve the deadline"],c:3,e:"The SM facilitates with data: (1) help the team voice concerns, (2) ground in velocity data, (3) redirect from 'do more' to 'choose wisely.' Supporting overcommitment (A) leads to failure. A flat no (B) is too blunt. Silence (C) ignores the SM's duty to protect the team."},
{q:"A developer says: 'Production support keeps pulling us off sprint work.' The SM should:",a:["Reduce velocity to account for interruptions","Establish a dedicated support rotation so the full team isn't disrupted","Add a 20% sprint buffer for unplanned work","Let the self-organizing team decide"],c:1,e:"This is an organizational impediment. A support rotation protects the team. Options A and C accommodate rather than solve. Option D ignores the SM's core duty: removing impediments the team can't remove alone. Fix the root cause first; adjust velocity only if you can't."},
{q:"Delivered software meets all requirements but isn't intuitive. In agile, what went wrong?",a:["The DoD didn't include usability criteria and real users weren't involved in sprint reviews","Development team didn't follow specs","Scrum Master didn't enforce quality","Nothing, since requirements were met"],c:0,e:"Meeting requirements but missing usability = incomplete requirements. The PO should involve actual users in reviews. If DoD doesn't include usability, it's never checked. Option D is a predictive mindset that misses agile's customer collaboration principle."},
{q:"Velocity over 6 sprints: 34, 28, 31, 22, 35, 30. How many points in the next 4 sprints?",a:["140 based on peak of 35","Approximately 120 based on average velocity of 30","128 based on upward trend","Impossible to forecast in agile"],c:1,e:"Average = 180/6 = 30. Forecast = 30 × 4 = 120. Use average velocity, not peak or trend. Agile absolutely supports forecasting using velocity. That's what velocity is for."},
{q:"Stakeholders love the increment, but the team knows significant technical debt exists. What should happen?",a:["Say nothing since stakeholders are happy","Transparently communicate the debt to the PO so it can be prioritized in the backlog","Fix all debt before delivering","SM handles it without involving the PO"],c:1,e:"Transparency is a core Scrum value. Hiding debt creates false progress. The PO needs visibility to make informed trade-offs: fix debt now (slower features) or accept risk (faster features, problems later). Technical debt is a business decision."},
{q:"In Kanban, work piles up in 'Code Review' while other columns have capacity. The team should:",a:["Have team members with available capacity help with reviews","Add more work upstream to keep everyone busy","Remove the WIP limit to clear the backlog","Move items past review since they're probably fine"],c:0,e:"Address the bottleneck by cross-training or pairing on reviews. Removing WIP limits (A) masks the problem. More upstream work (B) worsens it. Skipping reviews (D) introduces risk. Theory of Constraints: identify and exploit the bottleneck."},
{q:"Scrum vs. Kanban for a support project with unpredictable daily intake and varying item sizes?",a:["Scrum for sprint structure","Kanban for continuous flow without fixed timeboxes","Scrum for velocity tracking","Neither, use predictive"],c:1,e:"Kanban handles unpredictable, variable work through continuous flow. New items are pulled when capacity opens. Scrum works best with plannable batches. Match framework to work pattern: predictable batches = Scrum. Continuous flow = Kanban."},
{q:"Three retrospectives produced improvement actions. None implemented. The SM should:",a:["Add improvement actions as sprint backlog items","Cancel retrospectives since they're not working","Report the team's failure to management","Assign each action to someone with a hard deadline"],c:0,e:"Treat improvements as real work in the backlog. They compete for time and gain visibility. Canceling (A) kills inspect-and-adapt. Reporting to management (C) violates safe space. Hard deadlines (D) are too directive for self-organizing teams."},
{q:"The CEO requests a feature mid-sprint. Team is on track for the sprint goal. PO should:",a:["Add it to the current sprint since it's from the CEO","Cancel the sprint and start fresh","Acknowledge the request, add to backlog, prioritize for next sprint","Direct the CEO to submit a formal change request"],c:2,e:"Protect sprint commitment. Capture in backlog, prioritize for NEXT sprint. Adding mid-sprint (A) disrupts flow. Canceling (B) is extreme. Formal CR process (D) is too bureaucratic for agile. Urgency from authority doesn't override sprint integrity."},
{q:"Team wants to switch from 2-week to 4-week sprints because they feel rushed. SM should:",a:["Approve immediately since the team is self-organizing","Explore why they feel rushed before changing, since the root cause may be overcommitment","Deny the request since 2-week sprints are standard","Escalate to the PO"],c:1,e:"Feeling rushed might signal overcommitment, poor refinement, unclear stories, or interruptions. Changing sprint length treats the symptom. Explore root cause first. Self-organizing (A) doesn't mean every change is right. 2-week sprints aren't mandatory (C)."},
{q:"A senior says a story is 3 points. A junior says 8. This suggests:",a:["The senior is correct due to experience","Average to 5.5 as a compromise","The team needs discussion to reach shared understanding of scope and complexity","Story points are unreliable"],c:2,e:"Estimation disagreement is a FEATURE. It reveals different understandings. The discussion that follows is where value lives: the junior sees complexity the senior missed, or the senior knows a shortcut. Planning Poker deliberately surfaces these gaps. Averaging (B) skips the learning."},
{q:"Only one person can cancel a sprint. Who and when?",a:["SM when the team can't complete the goal","Sponsor when budget is exceeded","Team through majority vote","PO when the sprint goal becomes obsolete"],c:3,e:"Only the Product Owner. Only when the sprint goal becomes obsolete. Sprint cancellation is rare and disruptive. The SM (A), sponsor (B), and team (D) don't have this authority."},
{q:"A Scrum team consistently delivers an increment that passes testing but users report confusion. What should the team change?",a:["Hire a dedicated UX designer for the team","Include usability acceptance criteria in the Definition of Done and invite actual users to sprint reviews","Extend sprints to allow more testing time","Add a UAT phase after every third sprint"],c:1,e:"The fix is systemic: change what 'done' means (add usability criteria) AND change who gives feedback (real users in reviews). Hiring (A) might help but doesn't fix the process gap. Extending sprints (C) gives more time for the wrong tests. A UAT phase (D) delays feedback. Agile's strength is early, frequent user feedback."},
{q:"A spike in agile is BEST described as:",a:["A timeboxed investigation to reduce uncertainty before committing to a user story","A sudden increase in team velocity","A critical defect requiring immediate attention","An unplanned addition to the sprint backlog"],c:0,e:"A spike is a timeboxed research effort. Example: 'Spend 2 days investigating whether API X can support our authentication needs.' It produces KNOWLEDGE, not a deliverable. The team uses that knowledge to estimate the actual story. On the exam, spike = investigation to reduce uncertainty."},
{q:"What is the PRIMARY purpose of a sprint retrospective?",a:["Review completed work with stakeholders to gather feedback","Inspect the team's process and identify improvements for the next sprint","Plan the upcoming sprint's work by selecting backlog items","Estimate remaining user stories for future sprints"],c:1,e:"Sprint review (A) inspects the product with stakeholders. Sprint planning (C) selects work. Retrospective inspects the PROCESS: what went well, what didn't, what to improve. The retro is how the team gets better over time. Review = product. Retro = process. Planning = upcoming work."},
{q:"An information radiator in agile serves to:",a:["Provide a highly visible display of project status accessible to anyone walking by","Heat the team workspace for comfort","Send automated status reports to stakeholders","Replace all other forms of communication on the project"],c:0,e:"Information radiators (task boards, burndown charts, dashboards) are large, visible displays showing project status. They promote transparency without requiring meetings or reports. They don't replace communication (D) but supplement it with passive, always-available information."},
{q:"The Agile Manifesto values 'responding to change over following a plan.' This means:",a:["Plans are unnecessary in agile projects","The team should change direction whenever a stakeholder asks","Change requests should bypass all approval processes","Plans exist but the team adapts when circumstances change, since change is expected"],c:3,e:"The Manifesto doesn't say plans are useless (A). It says when change happens, the team adapts rather than rigidly following an outdated plan. Change still needs thoughtful handling (C is wrong). Not every stakeholder request warrants change (D). Plans are starting points, not contracts."},
{q:"A burndown chart shows remaining work ABOVE the ideal trendline for the last 3 days of a sprint. What does this indicate?",a:["The team is ahead of schedule and will finish early","The team is behind pace and may not complete all sprint commitments","The team's velocity has increased beyond expectations","The sprint backlog has decreased due to scope removal"],c:1,e:"Burndown tracks remaining work. The ideal line slopes down to zero. Remaining work ABOVE the ideal line means more work remains than expected at this point = behind pace. If the gap grows, the team likely won't finish all committed work. The SM should facilitate discussion about which items to prioritize."},
// ========== DOMAIN 4: BUSINESS ANALYSIS (38 Qs, ~27%) ==========
{q:"The warehouse manager says 'I need the system to be fast.' The BA should:",a:["Document it as 'system shall be fast'","Reject it as too vague","Add to backlog and refine during sprint planning","Ask clarifying questions to produce measurable requirements like 'lookups within 2 seconds'"],c:3,e:"'Fast' is subjective and untestable. The BA probes: 'What does fast mean? What scenario is too slow?' to yield measurable criteria. Documenting vagueness (A) passes the problem downstream. Rejection (B) is dismissive. Deferring (D) delays necessary analysis."},
{q:"Nurses describe their workflow differently from written procedures. The BA should:",a:["Trust nurses since end users know their workflow","Trust procedures since they're the organizational standard","Document both and let the sponsor decide","Observe nurses working, then reconcile practice against documentation"],c:3,e:"Neither source alone is reliable. Nurses might describe idealized workflows. Procedures might be outdated. Observation gives ground truth. Then reconcile: maybe docs need updating, maybe nurses need retraining. When sources conflict, gather additional evidence."},
{q:"47 scattered requirements from an elicitation session, many redundant, some conflicting. BA should do FIRST:",a:["Send to developers to begin on the clearest items","Prioritize with MoSCoW and start Must-haves","Schedule another session for more requirements","Organize using an affinity diagram, then analyze for conflicts and gaps"],c:3,e:"Before prioritizing (D) or working (A), organize what you have. Affinity diagrams group related items, revealing redundancies, conflicts, and gaps. More elicitation (C) adds chaos. BA workflow: Elicit → Organize → Analyze → Prioritize → Validate."},
{q:"A team member questions the RTM as unnecessary overhead. Best justification:",a:["PMO requires it for all projects","It ensures every requirement traces from origin through delivery, preventing missed requirements or unjustified features","It tracks the BA's personal work progress","It serves as a developer checklist"],c:1,e:"RTM provides bidirectional traceability: forward (requirement→design→code→test) and backward. This ensures: nothing forgotten, nothing built without justification (prevents gold plating), change impact is visible, test coverage verified. PMO compliance (A) is a reason but not the BEST."},
{q:"Two senior stakeholders disagree: one wants automated approval under $10K, the other wants all manual approval for compliance. BA should:",a:["Document both, investigate the compliance requirement, facilitate follow-up with evidence","Side with the higher-authority stakeholder","Set threshold at $5K as compromise","Escalate to sponsor immediately"],c:0,e:"Investigate WHY they disagree. If there's a real compliance requirement, it's a constraint, not a preference. The BA gathers evidence and facilitates. Compromise (C) is arbitrary and might violate regulations. Escalation (D) is premature before investigation."},
{q:"A user story reads: 'As a user, I want the system to be good.' Which INVEST criteria does it MOST violate?",a:["Independent and Small","Valuable and Negotiable","Estimable and Testable","Independent and Valuable"],c:2,e:"'Good' is subjective: can't be estimated (how big is 'good'?) and can't be tested (what test proves 'good'?). INVEST: Independent, Negotiable, Valuable, Estimable, Small, Testable. If you can't estimate or test it, refine it."},
{q:"Solution requirements in the RTM don't trace back to any business requirement. This indicates:",a:["RTM formatting errors","The solution exceeds needs, which adds value","Business requirements accidentally deleted","Requirements added without business justification, indicating scope creep or gold plating"],c:3,e:"Orphan requirements (no traced parent) mean someone added work without authorization. Building more than requested (D) wastes resources. Bidirectional traceability catches unjustified work going forward and missed requirements going backward."},
{q:"Three stakeholders of equal authority have conflicting priorities. The BA should:",a:["Escalate to sponsor for a binding decision","Recommend the customer-facing feature for highest ROI","Facilitate prioritization using objective criteria like business value and cost of delay","Build all three simultaneously by splitting the team"],c:2,e:"Objective criteria depersonalize the decision. Instead of 'whose department matters more,' it becomes 'which has highest value and cost of delay?' The BA facilitates. They don't decide, pick sides, or escalate prematurely."},
{q:"A product roadmap shows three releases over 12 months. Its PRIMARY purpose:",a:["Detailed schedule with specific dates","High-level view of features and delivery sequence showing product evolution","Replace the project management plan","Lock scope for all releases"],c:1,e:"Roadmap = strategic direction and sequencing. Not a detailed schedule (A), not a replacement for the PM plan (C), not a scope lock (D). Roadmaps should adapt as you learn."},
{q:"BDD uses Given/When/Then. For a login feature, which is CORRECT?",a:["Given the user clicks login, When they enter credentials, Then access is granted","Given requirements exist, When developers read them, Then they build correctly","Given the system is working, When any action occurs, Then the system responds","Given a registered user is on the login page, When they enter valid credentials and click submit, Then they are redirected to the dashboard within 2 seconds"],c:3,e:"BDD scenarios: specific, testable, observable behavior. B: Given (precondition) → When (action) → Then (measurable outcome). A reverses Given/When. C is untestably vague. D describes a process, not system behavior."},
{q:"Testing passes all cases but the solution doesn't align with business objectives from the business case. What went wrong?",a:["Traceability broke: solution requirements drifted from business requirements during elaboration","Poor test cases","Business objectives changed undocumented","Incorrect implementation"],c:0,e:"Tests validate the wrong thing because the chain broke between business and solution requirements. RTM prevents exactly this: ensuring solution requirements always trace to business requirements. Tests passed (A wrong). Implementation matched specs (D wrong)."},
{q:"Gap analysis output should be:",a:["Recommendation to purchase specific software","A cost-benefit analysis","A project charter","Identification of capabilities, process changes, and technology needed to bridge current to future state"],c:3,e:"Gap analysis identifies WHAT'S NEEDED between states, not HOW to get there (solution design) or WHETHER to proceed (cost-benefit). Output: capability gaps, process gaps, technology gaps, people gaps."},
{q:"Users report the new system works but hasn't improved productivity as promised. BA should:",a:["Close the project since technical requirements are met","Investigate why expected value isn't being realized by comparing actual performance against business case metrics","Revert to the old system","Document as lesson learned and move on"],c:1,e:"Meeting requirements but failing to deliver value means something broke. Investigate: training? Process change failure? Wrong assumptions? User resistance? Solution evaluation isn't just 'does it work?' It's 'does it deliver promised value?'"},
{q:"200 users across 5 countries, limited time and budget. Best elicitation technique:",a:["Individual interviews","Workshops at each location","Surveys and questionnaires distributed electronically","Focus groups per country"],c:2,e:"Surveys scale efficiently, don't require travel, can be translated. Match technique to constraints: large + dispersed + limited budget = surveys. Small group + complex = workshops. Deep understanding = interviews. Process = observation."},
{q:"The Delphi technique is useful because:",a:["It's the fastest collection method","It uses anonymous rounds preventing dominant personalities from influencing consensus","It eliminates need for follow-up","It requires only one expert"],c:1,e:"Delphi's key advantage: anonymity prevents groupthink and political pressure. Multiple rounds build consensus. It's NOT fast (A), DOES require rounds (C), and needs multiple experts (D). Use when politics or dominant personalities would skew results."},
{q:"A stakeholder with HIGH power and LOW interest should be managed by:",a:["Keeping them satisfied with periodic relevant updates","Keeping them closely managed with frequent updates","Monitoring with minimal effort","Keeping them informed through regular channels"],c:0,e:"High power + low interest = Keep Satisfied. They CAN impact your project but aren't engaged. Don't bore them with detail but don't ignore them. The four quadrants: High power/High interest = Manage Closely. High power/Low interest = Keep Satisfied. Low power/High interest = Keep Informed. Low power/Low interest = Monitor."},
{q:"Verification vs. validation of requirements:",a:["They're the same process","Verification checks quality standards; validation checks alignment with business goals","Validation always happens before verification","Only BAs do verification; stakeholders do validation"],c:1,e:"Verification: 'Did we build it right?' (meets quality specs). Validation: 'Did we build the right thing?' (meets business needs). Both matter. A system can pass verification (works correctly) but fail validation (solves the wrong problem). The exam tests this distinction frequently."},
{q:"Transition requirements are:",a:["Permanent features of the new system","Budget requirements for the transition period","The same as functional requirements","Temporary capabilities needed to move from current state to future state, like data conversion and training"],c:3,e:"Transition requirements are temporary: data migration, user training, parallel operations, process changeover. They're needed during transition but aren't permanent product features. Example: 'migrate 5 years of customer records from old system to new system.' Once done, the migration capability isn't needed."},
{q:"Root cause analysis is BEST described as:",a:["Identifying symptoms of a problem and addressing each one","Assigning responsibility for project failures","Creating a project schedule for problem resolution","Determining the underlying cause of a problem rather than addressing symptoms"],c:3,e:"RCA digs beneath symptoms to find fundamental causes. Addressing root causes prevents recurrence. Fixing symptoms (A) is temporary. Example: symptom = server crashes. Root cause = insufficient memory allocation during peak loads. Fix the allocation, not just restart the server."},
{q:"MoSCoW prioritization categorizes requirements as:",a:["Major, Optional, Standard, Critical, Outstanding, Wanted","Must have, Should have, Could have, Won't have","Mandatory, Optimal, Secondary, Critical, Ongoing, Wishful","Minimum, Optimal, Standard, Complete, Outstanding, Workable"],c:1,e:"Must have (essential, non-negotiable). Should have (important but not critical). Could have (nice-to-have, include if resources allow). Won't have (agreed to exclude for now, not never). The 'Won't have' category is important: it's a conscious decision, not a rejection."},
{q:"A BA performs a feasibility study. Its purpose is to:",a:["Test the final product before delivery","Determine if a proposed solution is viable from technical, economic, and organizational perspectives","Create the project schedule","Assign team resources to the project"],c:1,e:"Feasibility studies assess viability across dimensions: Technical (can we build it?), Economic (is it worth it?), Organizational (will the org adopt it?), Operational (can we maintain it?). This happens BEFORE committing to build. Not about testing (A), scheduling (C), or staffing (D)."},
// ========== CROSS-DOMAIN APPLICATION/JUDGMENT ==========
{q:"75% complete when the sponsor announces a 15% budget cut. PM should do FIRST:",a:["Perform impact analysis to determine deliverable scope within reduced budget, then present options","Continue as planned hoping costs come in under","Lay off team members immediately","Halt all work until resolved"],c:0,e:"Impact analysis first: what can you deliver with 85% budget? Present options: reduce scope, extend timeline, reduce quality (risky). Never act without understanding consequences. On the exam, when constraints change: analyze → present options → get decision → execute."},
{q:"Team member finds a security vulnerability exposing customer data. Fix delays launch 3 weeks. Sponsor says date can't move. PM should:",a:["Launch on time, patch later","Document the vulnerability, assess legal exposure, escalate to sponsor with recommendation to delay","Let the team member decide","Fix quietly without informing sponsor"],c:1,e:"Security vulnerabilities carry legal liability and reputational risk far exceeding 3 weeks of delay. Document, assess full impact, present to sponsor. Launching knowingly (A) could be negligent. Hiding delays (D) is dishonest. Ethical and legal obligations always override schedule pressure."},
{q:"PM takes over a troubled project midway. Incomplete docs, disengaged team, frustrated stakeholders. Prioritize FIRST:",a:["Review all documentation before doing anything","Meet individually with key stakeholders and team members to understand the situation","Call a team meeting for new ground rules","Review budget and schedule viability"],c:1,e:"Understand the human landscape first. Individual meetings let people speak candidly. Group meetings (C) suppress honesty. Documentation (A) and budget (D) matter but don't address the people problem causing dysfunction."},
{q:"CCB approves 10% scope increase. PM updates scope baseline but NOT schedule or cost baselines. Two months later project appears behind and over budget. What went wrong?",a:["CCB erred in approving the change","Team is underperforming","Original estimates were optimistic","PM failed integrated change control by not updating ALL affected baselines"],c:3,e:"10% more scope = more time and more money. By only updating scope, the PM created a measurement mismatch: performance judged against targets that don't reflect approved changes. It LOOKS like failure but it's a measurement error. Integrated means INTEGRATED: scope change → update schedule, cost, quality, risk."},
{q:"23 scope changes approved in 2 months, all through proper change control. What should concern the PM?",a:["Nothing, since process was followed","The CCB is too permissive","High volume suggests original scope was poorly defined or requirements inadequately captured during planning","This is normal for active projects"],c:2,e:"Following process doesn't mean everything is fine. 23 changes signals upstream problems: incomplete requirements, poor stakeholder understanding, vague scope. Investigate root cause. A restrictive CCB (B) doesn't fix why changes are being requested."},
{q:"Hybrid project: predictive infrastructure + agile software. Infrastructure falls 2 weeks behind, delaying software work. PM should:",a:["Crash infrastructure and adjust software backlog to prioritize items independent of infrastructure","Tell software team to wait","Switch entirely to agile","Remove infrastructure from scope"],c:0,e:"Address both streams: crash predictive work (add resources) + keep agile team productive on independent items. Switching (A) doesn't solve delay. Waiting (B) wastes capacity. Removing infrastructure (D) eliminates a necessary component. Apply the right technique to each work type."},
{q:"A PM calculates that adding 2 people to a 10-person team will improve communication. The communications formula shows this will actually:",a:["Reduce channels from 45 to 30","Increase channels from 55 to 78","Keep channels the same since 2 people is minimal","Increase channels from 45 to 66, adding complexity"],c:3,e:"10 people: 10(9)/2 = 45 channels. 12 people: 12(11)/2 = 66 channels. Adding 2 people increased channels by 21 (47% increase). Communication complexity grows faster than team size. This is why simply adding people to a late project often makes it later (Brooks's Law)."},
{q:"A project manager wants to use the most accurate estimating technique available. The project has detailed work packages and historical data from similar tasks. Which technique should they use?",a:["Analogous estimating based on the similar historical project","Expert judgment from senior team members","Bottom-up estimating using the detailed work packages","Parametric estimating using cost-per-unit from historical data"],c:2,e:"Bottom-up is the most accurate technique: estimate each work package individually and sum them. The PM has detailed work packages (required input for bottom-up). Analogous (A) is top-down and less accurate. Expert judgment (B) is subjective. Parametric (D) is good but bottom-up with detailed packages is more accurate. Accuracy hierarchy: Bottom-up > Parametric > Analogous."},
// ========== NEW: QUALITY TOOLS & CHARTS (Highly Testable) ==========
{q:"A Kanban team finds cards accumulating in the 'Testing' column while the 'In Progress' column empties out. What is the most likely cause and what mechanism surfaces it?",a:["The sprint is too long; shorten the timebox","Testing is a bottleneck; WIP limits are designed to surface this","Velocity is too high; reduce story points per sprint","The burndown is inaccurate; switch to a burnup chart"],c:1,e:"A widening downstream column is the textbook bottleneck signal. WIP limits exist to make this visible and force the team to address the bottleneck before pulling more work. Option A is wrong because Kanban has no sprints to shorten. Velocity (C) and burndown (D) are Scrum concepts. In Kanban, WIP limits are the primary mechanism for flow management and bottleneck detection."},
{q:"Which statement BEST distinguishes Scrum from Kanban?",a:["Scrum uses WIP limits; Kanban uses sprints","Scrum is flow-based and continuous; Kanban is timeboxed","Scrum delivers in fixed timeboxed iterations; Kanban manages continuous flow with WIP limits","Only Kanban uses a board to visualize work"],c:2,e:"Scrum = fixed iterations (sprints) with planning, review, retro. Kanban = continuous flow governed by WIP limits. Options A and B invert the two frameworks. Option D is false since both use visual boards. On the exam, the core distinction is timebox vs. flow."},
{q:"Midway through a release, the PO adds two new features. The team wants a chart that makes this scope increase visible alongside completed work. Which chart?",a:["Burndown chart","Velocity chart","Burnup chart","Pareto chart"],c:2,e:"Burnup plots completed work trending UP toward a separate total-scope line. When scope increases, the scope line jumps up, making the change visible. Burndown (A) would hide scope changes because it only shows remaining work. This is the burnup-vs-burndown trap on the exam. Burndown = remaining work. Burnup = completed work + total scope."},
{q:"A quality manager wants to identify which few defect categories account for the majority of customer complaints. Which tool?",a:["Scatter diagram","Control chart","Pareto chart","Cause-and-effect diagram"],c:2,e:"Pareto charts apply the 80/20 principle: a few causes drive most problems. Bars are sorted by frequency, with a cumulative percentage line. Scatter (A) shows correlation between variables. Control charts (B) monitor process stability over time. Fishbone/cause-and-effect (D) identifies root causes. On the exam, 'which few causes drive most problems?' = Pareto."},
{q:"A burndown chart's actual line is above the ideal line near the end of the sprint. What does this indicate?",a:["The team is ahead of schedule and will finish early","Scope was removed from the sprint","The team has more work remaining than planned and is behind","Velocity is increasing beyond expectations"],c:2,e:"On a burndown, the Y-axis is remaining work. The ideal line slopes down to zero. Actual ABOVE ideal = more remaining work than planned = behind. Below ideal would be ahead. This is a frequently tested visual interpretation question."},
{q:"An analyst plots 'hours of training' against 'number of defects' to see whether more training reduces defects. Which chart?",a:["Histogram","Scatter diagram","Cumulative flow diagram","Burnup chart"],c:1,e:"Two variables plotted to test a relationship = scatter diagram. If the dots trend downward (more training, fewer defects), there's a negative correlation. Histograms (A) show distribution of a single variable. CFD (C) is for Kanban flow analysis. Scatter diagrams answer: 'Is there a relationship between X and Y?'"},
{q:"Which chart would BEST help a Kanban team diagnose where in their workflow work is piling up over time?",a:["Velocity chart","Cumulative flow diagram","Pareto chart","Fishbone diagram"],c:1,e:"The CFD shows stacked bands for each workflow stage over time. When a band widens, work is accumulating in that stage (bottleneck). Velocity (A) is a Scrum metric. Pareto (C) categorizes problem frequency. Fishbone (D) identifies root causes. CFD is Kanban's diagnostic tool for flow problems."},
{q:"Why does timeboxing help counter Parkinson's Law?",a:["It adds more resources to fixed work packages","It allows scope to expand to fill available time","It fixes the duration so work cannot expand indefinitely; unfinished work moves to a later timebox","It removes deadlines to reduce team pressure"],c:2,e:"Parkinson's Law: work expands to fill the time available. Timeboxing counters this by fixing the time. If work isn't done when the timebox ends, it moves to the next one. The timebox doesn't expand. This is why sprints are fixed-length. Option B actually describes Parkinson's Law itself, not the counter to it."},
{q:"A control chart shows 7 consecutive data points on the same side of the mean. What does this indicate?",a:["The process is performing within acceptable limits","Normal random variation that requires no action","A non-random pattern suggesting the process is out of control (Rule of Seven)","The upper and lower control limits need to be recalculated"],c:2,e:"The Rule of Seven: seven or more consecutive points on the same side of the mean indicate a non-random pattern, even if all points are within control limits. This suggests a systematic cause (process drift, equipment degradation, etc.) that needs investigation. Points within limits but showing a pattern = out of control. On the exam, Rule of Seven is a classic quality control question."},
{q:"A histogram of project task durations shows most tasks clustered around 5 days with a long tail extending to 20 days. This distribution is:",a:["Normal (bell-shaped)","Right-skewed (positively skewed) with a risk of schedule overrun on outlier tasks","Left-skewed (negatively skewed)","Bimodal, indicating two distinct populations"],c:1,e:"Most values clustered left with a tail extending right = right-skewed (positively skewed). The long tail represents tasks that took much longer than typical. This tells the PM that while most tasks complete around 5 days, some carry significant schedule risk. Histograms show the distribution shape, which informs risk planning."},
// ========== NEW: PROCESS GROUPS & KNOWLEDGE AREAS ==========
{q:"Which process group contains the MOST processes?",a:["Initiating","Executing","Planning","Monitoring and Controlling"],c:2,e:"Planning has the most processes (24 out of 49). This makes sense since planning defines HOW the project will be executed across all knowledge areas. Initiating has 2, Executing has 10, Monitoring & Controlling has 12, Closing has 1. On the exam, knowing the relative size of each group helps with process sequencing questions."},
{q:"A PM completes the project deliverables, obtains stakeholder acceptance, and transitions the product. The PM then archives documents and releases the team. This describes which process group?",a:["Executing","Monitoring and Controlling","Planning","Closing"],c:3,e:"Closing involves: obtaining final acceptance, transitioning deliverables, archiving documents, releasing resources, collecting final lessons learned. The key signals are 'acceptance,' 'transition,' 'archive,' and 'release.' Executing (A) builds deliverables but doesn't close them out. M&C (B) monitors and adjusts."},
{q:"Validate Scope and Control Quality both involve inspecting deliverables. What is the key difference?",a:["Validate Scope is done by the team; Control Quality is done by the customer","Control Quality verifies deliverables meet requirements internally; Validate Scope obtains formal acceptance from the customer","They are the same process with different names","Validate Scope happens during planning; Control Quality happens during execution"],c:1,e:"Control Quality = internal verification ('Does it meet specs?'). Validate Scope = external acceptance ('Does the customer accept it?'). The sequence matters: Control Quality happens FIRST (internal check), then the verified deliverables go to Validate Scope (customer sign-off). On the exam, internal check = Control Quality. Customer acceptance = Validate Scope."},
{q:"Enterprise environmental factors (EEFs) differ from organizational process assets (OPAs) in that:",a:["EEFs are internal conditions; OPAs are external conditions","EEFs are conditions the team cannot control; OPAs are organizational knowledge and processes the team CAN use","There is no meaningful difference between them","EEFs are used only in planning; OPAs are used only in executing"],c:1,e:"EEFs are external conditions outside the team's control: market conditions, regulations, organizational culture, infrastructure. OPAs are internal assets the team can leverage: templates, historical data, lessons learned, policies, procedures. Key distinction: EEFs are constraints/conditions. OPAs are tools/resources. On the exam, 'government regulation' = EEF. 'Lessons learned from past projects' = OPA."},
{q:"Which process produces the project charter?",a:["Plan Scope Management in the Planning group","Direct and Manage Project Work in the Executing group","Develop Project Charter in the Initiating group","Develop Project Management Plan in the Planning group"],c:2,e:"The charter is created in the Initiating process group through the Develop Project Charter process. It formally authorizes the project. The charter comes BEFORE the project management plan (D). Plan Scope (A) and Direct & Manage (B) come later. Initiating has only two processes: Develop Project Charter and Identify Stakeholders."},
{q:"The 49 processes flow through 5 process groups. Which correctly orders them?",a:["Planning, Initiating, Executing, Closing, Monitoring and Controlling","Initiating, Planning, Executing, Monitoring and Controlling, Closing","Initiating, Executing, Planning, Monitoring and Controlling, Closing","Planning, Executing, Monitoring and Controlling, Initiating, Closing"],c:1,e:"The sequence is: Initiating (authorize) → Planning (how to execute) → Executing (do the work) → Monitoring & Controlling (track and adjust, runs parallel to executing) → Closing (formally end). M&C overlaps with executing since you monitor while work happens. On the exam, know this sequence and that M&C runs continuously alongside execution."},
// ========== NEW: CONFLICT RESOLUTION & TEAM MANAGEMENT ==========
{q:"Two team members have a technical disagreement about system architecture. The PM brings them together to find a solution that fully addresses both concerns. This conflict resolution technique is:",a:["Compromising, because both parties give up something","Forcing, because the PM is directing the resolution","Smoothing, because the PM is emphasizing areas of agreement","Collaborating (problem-solving), because the goal is a win-win solution addressing both perspectives"],c:3,e:"Collaborating seeks a win-win by working through the disagreement to find a solution satisfying both parties. Compromising (A) involves BOTH giving something up (lose-lose). Forcing (B) means one side wins by authority. Smoothing (D) emphasizes agreement while avoiding the real issue. On the exam, collaborating = best long-term resolution. Forcing = fastest. Compromising = middle ground. Smoothing = temporary. Avoiding = delay."},
{q:"A PM avoids discussing a scheduling conflict between two team members, hoping it will resolve on its own. This is an example of:",a:["Compromising","Smoothing","Forcing","Withdrawing (avoiding)"],c:3,e:"Withdrawing/avoiding = retreating from the conflict, postponing, or ignoring it. This is generally the LEAST effective technique since the conflict remains unresolved and often worsens. The PM may use it strategically for cooling-off periods, but as a default approach it's problematic. On the exam, avoiding/withdrawing = worst technique for lasting resolution."},
{q:"A PM tells the team: 'I understand you disagree, but we're going with Option A because we're out of time.' This is:",a:["Collaborating","Compromising","Forcing (directing)","Smoothing"],c:2,e:"Forcing/directing uses authority to end the conflict with one party winning. It's fast but creates resentment. The PM is choosing a side based on authority, not consensus. Useful in emergencies or when time is critical, but damages team dynamics if overused. On the exam, authority-based decision = forcing."},
// ========== NEW: RISK MANAGEMENT ==========
{q:"The risk response strategy of purchasing insurance for a construction project is an example of:",a:["Avoidance, eliminating the risk entirely","Mitigation, reducing the probability of the risk","Transference, shifting the financial impact to a third party","Acceptance, acknowledging the risk without action"],c:2,e:"Insurance transfers the FINANCIAL impact to the insurance company. The risk still exists (a hurricane can still hit), but the financial consequence shifts to the insurer. Avoidance (A) would mean not doing the construction during hurricane season. Mitigation (B) would mean reinforcing the structure. Acceptance (D) means no action taken. On the exam: insurance, warranties, bonds, contracts = transference."},
{q:"A project team decides to eliminate a risk by changing the project plan to avoid the risky activity entirely. This is:",a:["Transference","Mitigation","Acceptance","Avoidance"],c:3,e:"Avoidance eliminates the risk by changing the plan. Example: choosing a proven technology instead of an experimental one, or delaying outdoor work past hurricane season. The risk no longer exists because the triggering condition has been removed. Transference (A) shifts impact. Mitigation (B) reduces probability or impact. Acceptance (C) takes no action."},
{q:"A PM identifies a risk that a key team member might leave. The PM cross-trains two other team members on the critical skills. This is:",a:["Avoidance","Transference","Mitigation","Acceptance with contingency"],c:2,e:"Cross-training reduces the IMPACT if the team member leaves (others can step in). The risk still exists (they might still leave), but the consequence is reduced. This is mitigation: reducing probability or impact. Avoidance (A) would mean eliminating the possibility entirely (like signing a retention contract). Transference (B) would shift the impact to another party."},
// ========== NEW: ADDITIONAL HIGH-VALUE TOPICS ==========
{q:"A project has 12 stakeholders. How many potential communication channels exist?",a:["66","78","144","132"],c:0,e:"Formula: N(N-1)/2 = 12(11)/2 = 132/2 = 66 channels. If one stakeholder is added (13 total): 13(12)/2 = 78. Adding one person adds 12 new channels. This demonstrates why communication complexity grows exponentially with team size, and why a communication management plan is essential."},
{q:"A project manager is told the project must use only internal resources and must complete by December 31. These are examples of:",a:["Assumptions, because they may change","Risks, because they create uncertainty","Constraints, because they limit the team's options","Requirements, because they define what must be delivered"],c:2,e:"Resource restrictions and fixed deadlines are constraints: known limitations imposed on the project that restrict options. Assumptions (A) are believed true without proof. Risks (B) are uncertain events. Requirements (D) define deliverables, not project restrictions. On the exam: imposed limitations on resources, schedule, budget, or approach = constraints."},
{q:"The difference between gold plating and scope creep is:",a:["They are the same thing","Gold plating affects budget; scope creep affects schedule","Gold plating is always approved; scope creep is always rejected","Gold plating is team-initiated extras; scope creep is uncontrolled external changes bypassing change control"],c:3,e:"Gold plating: the team voluntarily adds features or work NOT requested by the stakeholder. Scope creep: uncontrolled scope growth from external requests that bypass change control. Both are problems. Gold plating wastes resources on unrequested work. Scope creep adds unapproved scope. On the exam, internally-added extras = gold plating. Externally-added unapproved scope = scope creep."},
{q:"The PM discovers that work is being performed that wasn't in the approved project scope, but the team says 'the customer will love it.' This is an example of:",a:["Scope creep from uncontrolled stakeholder requests","Gold plating by adding unrequested features","Proactive scope management","Value engineering"],c:1,e:"The team is adding work that wasn't requested or approved. Even if the customer might appreciate it, it wastes resources, wasn't authorized, and may introduce risk. All scope changes must go through change control. The team's good intentions don't override the process. On the exam, team adding unrequested work = gold plating. Always wrong."},
{q:"Which of the following is the CORRECT sequence during project closure?",a:["Release team → collect lessons learned → complete final report","Complete final report → collect lessons learned → release team","Collect lessons learned → complete final report → release team","Release team → complete final report → collect lessons learned"],c:2,e:"Collect lessons learned WHILE THE TEAM IS STILL TOGETHER (their insights are fresh). Then compile the final report (which includes the lessons learned). Then release the team. Options A and D release the team first, losing their input. Option B does the final report before capturing lessons, meaning the report lacks team insights."},
{q:"A PM is using a probability and impact matrix to prioritize risks. A risk with high probability and high impact should be classified as:",a:["Low priority since high-probability events are likely already accounted for","Medium priority requiring standard monitoring","High priority requiring immediate response planning","Acceptable risk requiring no action"],c:2,e:"The probability-impact matrix maps risks by likelihood and consequence. High probability + high impact = highest priority, requiring immediate attention and response planning. These risks can seriously derail the project. Low priority (A) contradicts the assessment. Medium (B) underreacts. Acceptable (D) ignores a serious threat."},
{q:"During planning, the team identifies that a new government regulation MIGHT be enacted that would require significant rework. This is currently:",a:["An issue requiring immediate resolution","A constraint limiting project options","A risk that should be added to the risk register with probability and impact assessment","An assumption that should be documented"],c:2,e:"'Might be enacted' = uncertain future event = risk. It hasn't happened yet (not an issue). It's not a current limitation (not a constraint). While you might ASSUME it won't happen, the proper treatment is to register it as a risk with probability and impact, then plan a response. On the exam: future uncertainty = risk. Current problem = issue."},
];

function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}

export default function CAPMFinal(){
  const[questions,setQuestions]=useState([]);
  const[idx,setIdx]=useState(0);
  const[answers,setAnswers]=useState({});
  const[showResult,setShowResult]=useState(false);
  const[sessionOver,setSessionOver]=useState(false);
  const[reviewMode,setReviewMode]=useState(false);
  const[missed,setMissed]=useState([]);
  const[reviewIdx,setReviewIdx]=useState(0);
  const ref=useRef(null);

  const start=useCallback(()=>{
    setQuestions(shuffle(Q));setIdx(0);setAnswers({});setShowResult(false);
    setSessionOver(false);setReviewMode(false);setMissed([]);setReviewIdx(0);
  },[]);
  useEffect(()=>{start();},[start]);

  const cur=reviewMode?missed[reviewIdx]:questions[idx];
  const qKey=reviewMode?`r${reviewIdx}`:`q${idx}`;
  const sel=answers[qKey]?.selected??null;
  const answered=answers[qKey]?.answered??false;

  const score=Object.values(answers).filter(a=>a.correct).length;
  const total=Object.values(answers).filter(a=>a.answered&&!a.review).length;
  const pct=total>0?Math.round((score/total)*100):0;

  const pick=(i)=>{
    if(answered)return;
    const correct=i===cur.c;
    const newA={...answers,[qKey]:{selected:i,answered:true,correct,review:reviewMode}};
    setAnswers(newA);setShowResult(true);
    if(!reviewMode&&!correct)setMissed(m=>[...m,{...cur}]);
  };

  const go=(dir)=>{
    if(reviewMode){
      const ni=reviewIdx+dir;
      if(ni<0)return;
      if(ni>=missed.length){setReviewMode(false);setSessionOver(true);return;}
      setReviewIdx(ni);
    }else{
      const ni=idx+dir;
      if(ni<0)return;
      if(ni>=questions.length){setSessionOver(true);return;}
      setIdx(ni);
    }
    setShowResult(false);
    if(ref.current)ref.current.scrollTop=0;
  };

  const qNum=reviewMode?reviewIdx+1:idx+1;
  const qTotal=reviewMode?missed.length:questions.length;
  const canBack=reviewMode?reviewIdx>0:idx>0;

  if(!cur&&!sessionOver)return null;

  return(
    <div ref={ref} style={{fontFamily:"'IBM Plex Mono','SF Mono',monospace",background:"var(--bg)",color:"var(--fg)",minHeight:"100vh",padding:"24px 16px",boxSizing:"border-box"}}>
      <style>{`
        :root{--bg:#0c0c12;--fg:#e4e2de;--card:#15151d;--border:#28283a;--accent:#6ee7b7;--accent-dim:#1a3a2a;--wrong:#f87171;--wrong-dim:#3a1a1a;--muted:#6b7280;--explain-bg:#1a1a28}
        @media(prefers-color-scheme:light){:root{--bg:#f5f5f0;--fg:#1a1a2e;--card:#fff;--border:#d1d5db;--accent:#059669;--accent-dim:#d1fae5;--wrong:#dc2626;--wrong-dim:#fee2e2;--muted:#6b7280;--explain-bg:#f9f9f6}}
        *{box-sizing:border-box;margin:0;padding:0}
      `}</style>

      <div style={{maxWidth:720,margin:"0 auto 28px",display:"flex",justifyContent:"space-between",alignItems:"baseline",borderBottom:"1px solid var(--border)",paddingBottom:14}}>
        <div>
          <div style={{fontSize:10,letterSpacing:3,color:"var(--muted)",textTransform:"uppercase",marginBottom:3}}>{reviewMode?"Reviewing Missed":"CAPM Exam Prep"}</div>
          <div style={{fontSize:18,fontWeight:600}}>{Q.length} Questions</div>
        </div>
        <div style={{textAlign:"right"}}>
          <div style={{fontSize:24,fontWeight:600,color:total===0?"var(--muted)":pct>=75?"var(--accent)":pct>=55?"#fbbf24":"var(--wrong)"}}>{total>0?`${pct}%`:"---"}</div>
          <div style={{fontSize:10,color:"var(--muted)",letterSpacing:1}}>{score}/{total}</div>
        </div>
      </div>

      {sessionOver?(
        <div style={{maxWidth:720,margin:"0 auto",padding:36,background:"var(--card)",border:"1px solid var(--border)",borderRadius:8,textAlign:"center"}}>
          <div style={{fontSize:40,fontWeight:600,marginBottom:6,color:pct>=75?"var(--accent)":pct>=55?"#fbbf24":"var(--wrong)"}}>{pct}%</div>
          <div style={{fontSize:12,color:"var(--muted)",marginBottom:6}}>{score} of {total}</div>
          <div style={{fontSize:12,marginBottom:28,color:"var(--muted)",lineHeight:1.6}}>
            {pct>=85?"Strong. You're ready.":pct>=70?"Passing range. Drill the misses.":pct>=55?"Close. Focus on explanations.":"Keep working. Explanations are where the learning happens."}
          </div>
          <div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap"}}>
            {missed.length>0&&!reviewMode&&(
              <button onClick={()=>{setReviewMode(true);setReviewIdx(0);setSessionOver(false);setShowResult(false);}} style={{padding:"11px 22px",background:"transparent",border:"1px solid var(--border)",color:"var(--fg)",borderRadius:6,cursor:"pointer",fontSize:11,fontFamily:"inherit"}}>
                Review {missed.length} missed
              </button>
            )}
            <button onClick={start} style={{padding:"11px 22px",background:"var(--accent)",color:"#0c0c12",border:"none",borderRadius:6,cursor:"pointer",fontSize:11,fontWeight:600,fontFamily:"inherit"}}>New session</button>
          </div>
        </div>
      ):(
        <div style={{maxWidth:720,margin:"0 auto"}}>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
            <div style={{fontSize:10,color:"var(--muted)",letterSpacing:1}}>{qNum}/{qTotal}</div>
            <div style={{flex:1,height:2,background:"var(--border)",borderRadius:1}}>
              <div style={{height:2,background:"var(--accent)",borderRadius:1,width:`${(qNum/qTotal)*100}%`,transition:"width 0.3s"}}/>
            </div>
          </div>

          <div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:8,padding:"22px 18px",marginBottom:12}}>
            <div style={{fontSize:13,lineHeight:1.85,fontWeight:500}}>{cur.q}</div>
          </div>

          <div style={{display:"flex",flexDirection:"column",gap:5,marginBottom:14}}>
            {cur.a.map((opt,i)=>{
              const isC=i===cur.c,isS=i===sel;
              let bg="var(--card)",bc="var(--border)";
              if(answered){if(isC){bg="var(--accent-dim)";bc="var(--accent)";}else if(isS){bg="var(--wrong-dim)";bc="var(--wrong)";}}
              return(
                <button key={i} onClick={()=>pick(i)} disabled={answered} style={{
                  display:"flex",alignItems:"flex-start",gap:10,padding:"11px 14px",
                  background:bg,border:`1px solid ${bc}`,borderRadius:6,color:"var(--fg)",
                  cursor:answered?"default":"pointer",fontSize:12.5,lineHeight:1.75,
                  fontFamily:"inherit",textAlign:"left",transition:"all 0.15s",
                  opacity:answered&&!isC&&!isS?0.3:1,
                }}>
                  <span style={{flexShrink:0,width:20,height:20,borderRadius:3,border:`1px solid ${bc}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:600,marginTop:2,color:answered&&isC?"var(--accent)":answered&&isS&&!isC?"var(--wrong)":"var(--muted)"}}>{String.fromCharCode(65+i)}</span>
                  <span>{opt}</span>
                </button>
              );
            })}
          </div>

          {answered&&(
            <div style={{background:"var(--explain-bg)",border:`1px solid ${sel===cur.c?"var(--accent)":"var(--wrong)"}`,borderRadius:8,padding:"16px 18px",marginBottom:14}}>
              <div style={{fontSize:10,fontWeight:600,letterSpacing:2,textTransform:"uppercase",marginBottom:10,color:sel===cur.c?"var(--accent)":"var(--wrong)"}}>{sel===cur.c?"Correct":"Incorrect"}</div>
              <div style={{fontSize:12.5,lineHeight:1.9,color:"var(--fg)",opacity:0.9}}>{cur.e}</div>
            </div>
          )}

          <div style={{display:"flex",gap:8}}>
            {canBack&&(
              <button onClick={()=>go(-1)} style={{flex:1,padding:"12px",background:"var(--card)",color:"var(--fg)",border:"1px solid var(--border)",borderRadius:6,cursor:"pointer",fontSize:12,fontWeight:600,fontFamily:"inherit"}}>Back</button>
            )}
            {answered&&(
              <button onClick={()=>go(1)} style={{flex:canBack?2:1,padding:"12px",background:"var(--accent)",color:"#0c0c12",border:"none",borderRadius:6,cursor:"pointer",fontSize:12,fontWeight:600,fontFamily:"inherit"}}>
                {(reviewMode&&reviewIdx+1>=missed.length)||(!reviewMode&&idx+1>=questions.length)?"See Results":"Next"}
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
