import { useState, useEffect, useCallback, useRef } from "react";

const QUESTIONS = [
// ===== DOMAIN 1: PM FUNDAMENTALS & CORE CONCEPTS (36 questions) =====
{q:"A project manager discovers that a critical vendor has gone bankrupt and cannot deliver essential components. The project is 60% complete. The PM has identified two alternative vendors, but switching will add 3 weeks and $40,000. What should the PM do FIRST?",a:["Submit a change request documenting the schedule and cost impact, then present alternatives to the sponsor","Select the more cost-effective alternative vendor and begin the transition immediately to minimize delay","Invoke the risk response plan, since vendor failure should have been identified as a risk during planning","Notify the sponsor and request guidance on whether to continue or terminate the project"],c:2,e:"This risk event has materialized into an issue. If proper risk planning was done, vendor failure would be in the risk register with a documented response. The FIRST action is to check existing plans. Option A (change request) is a likely NEXT step, but you check plans before creating new ones. Option B skips approval entirely, violating change control. Option D is reasonable but premature since you haven't checked your own risk plans yet. On the exam, when a risk event occurs: check risk register first > invoke planned response > assess impact > submit change request > get approval > execute."},
{q:"The project charter has been approved. The PM begins identifying stakeholders and discovers a key department head was excluded during charter development. This person now opposes the project. What should the PM do?",a:["Proceed since the charter is already approved and has executive backing","Meet with the department head to understand their concerns and find alignment before proceeding","Request the sponsor override the department head's objections","Revise the charter to incorporate the department head's requirements"],c:1,e:"Stakeholder engagement is about building relationships, not forcing compliance. The department head has legitimate concerns from being excluded. Meeting them addresses the root cause: they feel unheard. Proceeding without engagement (A) creates an active opponent who can undermine the project. Escalating to the sponsor (C) is adversarial. Revising the charter (D) may eventually happen, but understanding concerns comes first. On the exam, when a stakeholder opposes you, your first move should always be to listen and understand, not to overpower or ignore."},
{q:"During a status meeting, a team member says a vendor may not deliver components on time. Another says the vendor has always been reliable and the concern is unnecessary. How should the PM categorize these perspectives?",a:["The first is raising an issue; the second is making an assumption","The first is identifying a constraint; the second is documenting a lesson learned","The first is documenting an assumption; the second is identifying an opportunity","The first is identifying a risk; the second is making an assumption"],c:3,e:"The first team member identifies a RISK: an uncertain future event that could negatively impact the project. It hasn't happened yet, so it's not an issue. The second makes an ASSUMPTION: treating something as true without proof. Assumptions carry hidden risk because if they prove wrong, the risk materializes. On the exam: Risk = future uncertainty. Issue = current problem. Assumption = believed true without proof. Constraint = limiting factor. These four are frequently tested together in scenario questions."},
{q:"A PM notices a high-performing team member has become disengaged and is missing deadlines after being passed over for a promotion. According to Maslow's hierarchy, which need is most likely unmet?",a:["Safety needs, because their job security feels threatened","Belonging needs, because they feel excluded from the team","Self-actualization needs, because they can't reach their full potential","Esteem needs, because their desire for recognition and achievement is unmet"],c:3,e:"Maslow's hierarchy (bottom to top): Physiological, Safety, Belonging, Esteem, Self-actualization. Being passed over for promotion directly impacts esteem (recognition, respect, achievement). The team member previously performed well (lower needs met) but became disengaged after the promotion decision. Safety (A) relates to job security, not recognition. Belonging (B) relates to team relationships. Self-actualization (D) requires esteem needs to be met first. On the exam, apply motivation theories to the specific scenario rather than just reciting definitions."},
{q:"A PM is assigned to a project where team members report to functional managers. The PM has limited authority and must negotiate for resources. What type of organization is this?",a:["Functional organization where the PM has almost no authority","Weak matrix organization where the PM has limited authority","Balanced matrix organization where authority is shared equally","Projectized organization where the PM has full authority"],c:1,e:"The key signals: PM exists but has limited authority and must negotiate for resources. In a functional organization, the PM would have almost NO authority (might just be a coordinator/expeditor). In a weak matrix, the PM exists but with limited authority, which matches. In a balanced matrix, authority is shared more equally. On the exam, pay attention to degree of PM authority: none = functional, limited = weak matrix, shared = balanced, significant = strong matrix, full = projectized."},
{q:"The project sponsor pressures the PM to begin executing work immediately. The charter is approved but no project management plan exists. What should the PM do?",a:["Create a high-level plan and begin execution simultaneously on well-understood deliverables","Begin work on the least risky deliverables while developing the plan in parallel","Explain that a project management plan must be developed before execution can begin","Ask the team to start work based on the scope description in the charter"],c:2,e:"Without a project management plan, you have no baselines, no quality standards, no risk plan, and no communication strategy. Starting work without these means you can't measure progress or control changes. Options A, B, and D all involve starting work without proper planning. On the exam, when a sponsor pressures you to skip planning, the correct answer pushes back professionally. The charter authorizes the project but doesn't tell you HOW to execute."},
{q:"During project closure, the PM discovers lessons learned were never collected during the project. What is the BIGGEST problem with this?",a:["The project closure report will be incomplete and may not meet PMO standards","The sponsor may not approve formal project closure without documented lessons","Team members have dispersed and their insights about what worked and what failed are lost forever","The PM will need to schedule a retrospective meeting, delaying closure"],c:2,e:"The biggest loss is institutional knowledge. Team members who experienced problems, found creative solutions, or identified what worked are now gone. Their insights die with their departure. An incomplete report (A) is a symptom. The sponsor (B) and scheduling concern (D) are secondary. The real damage is to FUTURE projects that won't benefit from this team's experience. This is why PMI emphasizes continuous lessons learned collection throughout the project, not just at the end."},
{q:"A PM evaluates two potential projects. Project A has an NPV of $500,000. Project B has an NPV of $350,000. Both require similar resources and timelines. Which should the PM recommend?",a:["Project B because lower NPV indicates lower risk exposure","Project A because higher NPV indicates greater expected return on investment","Either project since NPV alone is never sufficient for project selection","Project B because it likely has a shorter payback period"],c:1,e:"NPV represents the present value of all future cash flows minus the investment. Higher NPV = more value created. Project A returns $500K more than its cost in today's dollars. Lower NPV (A) doesn't mean lower risk since NPV already accounts for time value of money. While NPV alone may not always suffice (C), the question states similar resources and timelines, removing those variables. NPV says nothing about payback period (D). On the exam: higher NPV = better. Shorter payback period = better. Higher IRR = better."},
{q:"The cost of quality includes prevention costs, appraisal costs, and failure costs. A company invests in developer training and code review processes. This falls under:",a:["Appraisal costs because it evaluates work quality through reviews","Internal failure costs because it catches problems before they reach customers","Prevention costs because it aims to stop defects before they occur","External failure costs because it ultimately prevents customer-facing defects"],c:2,e:"Prevention costs are investments to PREVENT defects: training, process improvements, quality planning, design reviews. Appraisal costs are for DETECTING defects: testing, inspections, audits. Internal failure = defects found BEFORE delivery (rework, scrap). External failure = defects found AFTER delivery (warranty, lawsuits). Training and code reviews stop defects at the source = prevention. On the exam: Prevention = stop it. Appraisal = find it. Internal failure = fix it before shipping. External failure = fix it after the customer finds it."},
{q:"A stakeholder tells the PM: 'The system must handle 10,000 concurrent users with less than 2 seconds response time.' This is an example of:",a:["A non-functional requirement describing how the system must perform","A business requirement describing organizational needs and objectives","A functional requirement describing specific system behavior","A constraint limiting the project team's technical options"],c:0,e:"Performance criteria (concurrent users, response time) are non-functional requirements describing HOW the system performs, not WHAT it does. Functional requirements (A) describe specific behaviors ('the system shall process refunds'). Business requirements (B) describe organizational needs ('improve satisfaction by 20%'). A constraint (D) restricts the project itself (budget, timeline). Non-functional requirements include: performance, security, reliability, scalability, usability, availability. On the exam, ask: does it describe a feature (functional) or a quality characteristic (non-functional)?"},
{q:"A PM is facilitating a brainstorming session. One team member immediately criticizes another's idea. What should the PM do?",a:["Allow the criticism since filtering weak ideas early saves time","Ask the critic to present their own solution before criticizing others","End the brainstorming and switch to a Delphi technique for anonymous input","Remind the team that brainstorming requires capturing all ideas without judgment first"],c:3,e:"Brainstorming's fundamental rule: no criticism during idea generation. Critiquing kills creativity and discourages participation. The correct process: generate freely, THEN evaluate. Allowing criticism (A) violates the core principle. Redirecting to the critic (B) doesn't address the process violation. Switching techniques (C) gives up too easily. On the exam, brainstorming questions always test: evaluation comes AFTER generation, not during it. The PM's facilitator role is to protect the process."},
{q:"The project team is in the process of establishing ground rules, developing trust, and working through disagreements constructively. According to Tuckman's model, they are in which stage?",a:["Forming, because they are still getting to know each other","Storming, because disagreements indicate unresolved conflict","Norming, because they are establishing how to work together","Performing, because they are productively working through issues"],c:2,e:"Key phrase: 'establishing ground rules, developing trust, working through disagreements constructively.' This is norming. In forming, people are polite but cautious. In storming, conflict is raw and unresolved. In norming, they've worked through the worst and are BUILDING working agreements. In performing, those agreements are established and productivity is high. The storming vs. norming distinction trips people up: storming = active unresolved conflict. Norming = team is resolving conflict and building norms. Performing = norms are in place, conflict is handled smoothly."},
{q:"A PM discovers a team member has been inflating time estimates to create personal schedule buffer. This violates which PMI Code of Ethics value?",a:["Responsibility, because they aren't fulfilling their duty to the project","Fairness, because they are taking resources from other team members","Respect, because they are undermining trust within the team","Honesty, because they are providing inaccurate information"],c:3,e:"Inflating estimates is fundamentally dishonest: providing inaccurate information to create hidden buffer. While it touches responsibility (A) and trust/respect (C), and could be seen as unfair (B), the PRIMARY violation is honesty since the core act is deliberately providing false data. PMI's four values: Responsibility, Respect, Fairness, Honesty. On the exam, identify the PRIMARY value violated by looking at the core action, not the downstream effects."},
{q:"A project requires strict regulatory compliance with complete documentation and phase-gate approvals before proceeding to the next phase. Which approach is most appropriate?",a:["Adaptive approach with detailed sprint documentation to satisfy regulators","Hybrid approach combining agile development with predictive compliance tracking","Iterative approach with regulatory checkpoints at the end of each cycle","Predictive approach with phase-gate reviews ensuring sequential completion"],c:3,e:"Key signals: strict regulations, complete documentation BEFORE moving to next phase, approval signatures required. This is predictive with phase gates. Each phase must be fully completed and approved before the next begins. Adaptive (A) doesn't naturally produce the sequential documentation trail. Hybrid (B) could work in some contexts but the question specifically requires completion before proceeding, which is pure predictive. Iterative (D) revisits work, conflicting with sequential approval. On the exam, 'must complete before proceeding' + 'regulatory compliance' + 'full documentation' = predictive with gates."},
{q:"Work performance data, work performance information, and work performance reports represent different levels of project data. What is the correct progression?",a:["Reports are created first, then analyzed into information, then reduced to raw data","Information is gathered first, then transformed into data, then compiled into reports","Data is collected as raw observations, then analyzed into information, then compiled into reports for stakeholders","Data and information are the same thing, and reports summarize both"],c:2,e:"The progression is: Data (raw, unanalyzed observations from executing processes, e.g., '35% of tasks complete') > Information (analyzed and contextualized data from monitoring processes, e.g., 'we are 10% behind schedule') > Reports (formatted presentations for stakeholders, e.g., 'status report showing schedule variance and corrective actions'). This hierarchy matters because each level serves different audiences. The PM transforms data into information through analysis, then packages information into reports for decision-makers. On the exam, remember the flow: raw data > analyzed information > stakeholder reports."},
{q:"The project management plan differs from project documents in that:",a:["The project management plan contains subsidiary plans and baselines; project documents like the risk register and stakeholder register support the project but are not part of the formal plan","Project documents are created during planning while the management plan is created during execution","The project management plan only contains the schedule and budget baselines","There is no meaningful difference; all project paperwork is part of the project management plan"],c:0,e:"The PM plan is a formal, integrated document containing subsidiary plans (scope management plan, schedule management plan, etc.) and baselines (scope, schedule, cost). Project documents are separate: risk register, stakeholder register, issue log, lessons learned register, change log. They SUPPORT the project but aren't formally part of the management plan. On the exam, know what's IN the plan (subsidiary plans + baselines) versus what's a separate supporting document. This distinction appears frequently."},
{q:"A functional manager and PM disagree about resource allocation. The PM needs a developer full-time, but the functional manager wants to keep them on operations work. They have equal authority. What should the PM do FIRST?",a:["Escalate to the sponsor with documentation of the schedule impact if the resource isn't available","Accept partial availability and adjust the project schedule accordingly","Negotiate with the functional manager to understand their constraints and explore compromises like part-time availability","Hire a contractor to replace the developer and avoid the conflict entirely"],c:2,e:"Equal authority (balanced matrix) means neither can overrule the other. Escalating immediately (A) skips negotiation and damages the relationship. Accepting passively (B) fails the project without trying. Hiring a contractor (D) avoids the conversation and adds cost. Negotiation (C) is the right first move: understand the emergency, explore middle ground (50/50? delayed start?), document impact. If negotiation fails, THEN escalate with data. On the exam, in matrix organizations, negotiation always comes before escalation."},
{q:"A project can be a vehicle for change because:",a:["Projects always reduce organizational costs through efficiency improvements","Projects create unique products, services, or results that transition the organization from current state to future state","Projects eliminate operational work by automating existing processes","Projects are permanent organizational structures that drive continuous improvement"],c:1,e:"Projects drive change by creating unique deliverables that move the organization from a current state to a desired future state. They're temporary by definition (D is wrong). They don't always reduce costs (A) or eliminate operations (C). The PMBOK 7th Edition emphasizes projects as vehicles for delivering value through change. On the exam, understand that projects exist to create change, and change management is essential because not all stakeholders will embrace that change willingly."},
{q:"The PM is comparing the roles of project manager and project sponsor. Which statement is CORRECT?",a:["The sponsor manages day-to-day project activities while the PM provides strategic direction","The PM is responsible for achieving project objectives; the sponsor provides funding, support, and resolves issues beyond the PM's authority","The sponsor and PM share equal responsibility for all project decisions","The PM reports to the sponsor only during the initiation phase"],c:1,e:"The PM leads daily execution toward project objectives. The sponsor champions the project at the organizational level: provides funding, removes organizational barriers, and resolves escalated issues. The sponsor does NOT manage day-to-day activities (A). They don't share equal responsibility for all decisions (C). The relationship continues throughout the project, not just initiation (D). On the exam, the distinction is: PM = tactical execution. Sponsor = strategic support and organizational authority."},
{q:"A project has deliverables that must comply with government regulations. Which of the following is a constraint versus an assumption?",a:["Constraint: the budget is fixed at $500K. Assumption: regulations won't change during the project","Constraint: the team assumes regulations won't change. Assumption: the budget is fixed at $500K","Constraint: the team has 10 developers. Assumption: the project will take 12 months","Both the budget and regulatory stability are constraints since neither can be controlled"],c:0,e:"A constraint is a known limiting factor imposed on the project (fixed budget, regulatory requirements, deadline). An assumption is something believed true without proof (regulations won't change). The budget being fixed at $500K is a real, known limitation = constraint. Believing regulations won't change is treating an uncertain future as certain = assumption. Assumptions carry risk because if they prove false, they impact the project. On the exam, constraints are KNOWN limitations. Assumptions are BELIEVED truths. Risks are FUTURE uncertainties."},
// ===== DOMAIN 2: PREDICTIVE/PLAN-BASED (17 questions) =====
{q:"A project has three network paths: Path 1: A(3)>B(5)>C(2)=10 days. Path 2: A(3)>D(4)>E(6)=13 days. Path 3: A(3)>F(3)>G(3)=9 days. Activity D is delayed by 2 days. What is the impact?",a:["The project is delayed by 2 days because D is on the critical path with zero float","No impact because D has 3 days of float available","The project is delayed by 1 day because D has 1 day of float and the delay exceeds it","The project finish date changes from 13 to 14 days"],c:0,e:"Path 2 (A>D>E = 13 days) is the longest path = critical path. Critical path activities have ZERO float. A 2-day delay to D makes Path 2 = 15 days, delaying the project by 2 days. Path 1 has 3 days float (13-10). Path 3 has 4 days float (13-9). On the exam: always identify the critical path first (longest path), then assess impact. Critical path activities have zero float. Non-critical activities can slip within their float."},
{q:"BAC = $300,000. The team has spent $120,000 and completed 30% of the work. They should have completed 40% by now. What is the SPI?",a:["0.90, indicating slightly behind schedule","0.75, indicating significantly behind schedule","1.33, indicating ahead of schedule","0.67, indicating severely behind schedule"],c:1,e:"EV = 30% x $300K = $90K. PV = 40% x $300K = $120K. SPI = EV/PV = $90K/$120K = 0.75. The team completes only 75 cents of planned work per dollar planned. They're 25% behind schedule. Notice: AC ($120K) wasn't needed for SPI. The exam gives extra data to see if you grab wrong numbers. SPI only uses EV and PV. CPI uses EV and AC. SPI < 1 = behind. SPI > 1 = ahead. SPI = 1 = on target."},
{q:"Using the same data (BAC=$300K, AC=$120K, 30% complete), what is the CPI and what does it mean?",a:["CPI = 0.75, meaning the project is over budget earning only 75 cents per dollar spent","CPI = 1.33, meaning the project is under budget and performing efficiently","CPI = 0.90, meaning the project is slightly over budget","CPI = 1.00, meaning cost performance is exactly on target"],c:0,e:"EV = $90K. AC = $120K. CPI = EV/AC = $90K/$120K = 0.75. For every dollar spent, you get $0.75 of work. This project is BOTH behind schedule (SPI=0.75) AND over budget (CPI=0.75). That's serious. When both are below 1, immediate corrective action is needed. The exam asks you to calculate both and interpret the combination. The formulas: SPI = EV/PV (schedule). CPI = EV/AC (cost). Memory trick: schedule uses Planned Value, cost uses Actual Cost."},
{q:"Continuing (BAC=$300K, CPI=0.75), what is the EAC and what does it tell the sponsor?",a:["EAC = $225,000, the project will finish under budget","EAC = $400,000, the project will cost $100,000 more than the original $300K budget","EAC = $300,000, the project will finish on budget despite current overruns","EAC = $180,000, only $180,000 remains to be spent"],c:1,e:"EAC = BAC/CPI = $300K/0.75 = $400,000. If spending continues at this rate, total cost will be $400K instead of $300K. That's a $100K overrun. ETC (remaining cost) = EAC - AC = $400K - $120K = $280K. VAC = BAC - EAC = $300K - $400K = -$100K (negative = over budget). The sponsor needs this forecast to decide: increase budget, reduce scope, or accept the overrun. On the exam, master the chain: EV > CPI > EAC > ETC > VAC."},
{q:"The TCPI for a project is calculated at 1.35. What does this tell the PM?",a:["The project is performing well with a CPI of 1.35 on current work","The project will finish 35% under budget at the current rate","The project has a 35% probability of finishing on budget","The team needs to achieve a CPI of 1.35 on ALL remaining work to finish within budget, which is very difficult"],c:3,e:"TCPI = (BAC-EV)/(BAC-AC). It shows the efficiency you MUST achieve on remaining work to meet budget. TCPI of 1.35 means earning $1.35 per dollar spent going forward. If current CPI is below 1.0, jumping to 1.35 is extremely difficult. Generally: TCPI > 1.0 = hard to meet budget. TCPI >> 1.0 = likely unrealistic. This signals the PM should discuss a budget increase or scope reduction with the sponsor. On the exam, TCPI answers: 'Can we still finish on budget?'"},
{q:"A PM needs to compress the schedule. Option 1: add a second team to Activity X, reducing it from 10 to 7 days at $15K extra cost. Option 2: start Activity Y two days before Activity X finishes. Which techniques are these?",a:["Option 1 is fast tracking; Option 2 is crashing","Both are examples of crashing with different approaches","Option 1 is crashing; Option 2 is fast tracking","Option 1 is resource leveling; Option 2 is schedule compression"],c:2,e:"Adding resources to compress duration at additional cost = crashing. Starting a successor before the predecessor finishes (overlapping sequential activities) = fast tracking. Crashing always costs more money. Fast tracking increases risk (if X changes, Y may need rework). Resource leveling smooths usage and typically EXTENDS the schedule. On the exam: Crashing = more money for less time. Fast tracking = more risk for less time. Both only work on critical path activities."},
{q:"Three-point estimate: Optimistic=4 days, Most Likely=7 days, Pessimistic=16 days. Using PERT, what is the expected duration?",a:["9 days using the simple average","7 days using the most likely estimate","8 days using the PERT weighted formula","10 days because the pessimistic skew adds extra time"],c:2,e:"PERT = (O + 4M + P) / 6 = (4 + 28 + 16) / 6 = 48/6 = 8 days. The formula weights most likely 4x because it's the best predictor. Simple average (A) would be (4+7+16)/3 = 9, which is a common wrong answer. The pessimistic estimate (16) is far from most likely, creating right-skewed risk. On the exam, know both formulas: PERT weighted = (O+4M+P)/6. Triangular (simple) = (O+M+P)/3. PERT is more commonly tested."},
{q:"Activity A has Early Start=Day 1, Early Finish=Day 5, Late Start=Day 3, Late Finish=Day 7. What is the total float?",a:["2 days, meaning the activity can slip 2 days without delaying the project","0 days, meaning the activity is on the critical path","5 days, meaning the activity has significant scheduling flexibility","7 days, meaning the activity can start anytime in the first week"],c:0,e:"Total Float = Late Start - Early Start = 3 - 1 = 2 days. (Or Late Finish - Early Finish = 7 - 5 = 2 days.) This activity can slip 2 days without affecting the project end date. Since float > 0, it's NOT on the critical path. Critical path activities have float = 0. On the exam: Float = LS - ES = LF - EF. Zero float = critical path. The exam may give you ES/EF/LS/LF and ask you to calculate."},
{q:"Activity A (15 days) and Activity B (10 days) run in parallel. Activity C (20 days) starts after BOTH complete. What is the earliest C can start?",a:["Day 16, because C waits for both predecessors and A is longer, finishing Day 15","Day 11, because B finishes first and C can begin after the shorter activity","Day 26, because A and B durations are added sequentially before C","Day 21, after the average of both predecessor durations"],c:0,e:"C requires BOTH A and B complete. They run in parallel. A finishes Day 15, B finishes Day 10. C waits for the LONGER one. C starts Day 16. Option A makes the critical error of starting after the shorter path. When activities converge, the successor waits for the LATEST predecessor. This convergence point is often where the critical path runs. On the exam, parallel activities with a common successor: successor starts after the SLOWEST parallel path completes."},
{q:"A PM is managing a construction project. Foundation work is complete, but the framing permit hasn't been issued yet. The PM estimates a 5-day wait. What schedule tool accounts for this?",a:["Add 5 days of float to the framing activity to absorb the delay","Fast track framing to overlap with the permit processing period","Crash the permit process by hiring an expediter to speed approval","Add a 5-day lag between foundation completion and framing start"],c:3,e:"A lag is a mandatory waiting period between predecessor and successor. The permit wait is a required delay built into schedule logic. You can't start framing without it. Float (A) is existing flexibility, not something you add. Fast tracking (B) doesn't apply since you can't start framing without the permit. Crashing (C) assumes you can speed up an external process. On the exam, lags represent real-world mandatory waits: curing time, approval cycles, regulatory processes, permit issuance."},
{q:"The PM and team cannot decompose a work package because the technology hasn't been selected. They plan to decompose it in 3 months when more is known. This is called:",a:["Progressive elaboration, the natural evolution of project details over time","Scope creep, because undocumented scope is being added later","Rolling wave planning, a deliberate strategy of detailed near-term planning with high-level future planning","Decomposition, the standard technique of breaking work into smaller components"],c:2,e:"Rolling wave planning deliberately plans near-term work in detail while leaving future work at a higher level, with intent to elaborate later. Progressive elaboration (A) is the general concept that details become clearer over time, not a specific planning technique. Scope creep (B) is uncontrolled changes. Decomposition (D) is the act of breaking things down, not the strategy of when to do it. On the exam: rolling wave = intentional planning technique. Progressive elaboration = natural evolution."},
{q:"BAC = $600,000. At the halfway point, EV = $270,000 and AC = $300,000. The sponsor asks: 'Can we still finish on budget?' Which metric BEST answers this?",a:["CPI = 0.90, showing current cost efficiency","EAC = $666,667, forecasting total project cost","SPI, showing whether schedule performance affects cost","TCPI = 1.10, showing the efficiency required on remaining work to meet the budget"],c:3,e:"TCPI directly answers 'can we finish on budget?' It calculates the efficiency needed on remaining work. TCPI = (BAC-EV)/(BAC-AC) = ($600K-$270K)/($600K-$300K) = $330K/$300K = 1.10. The team needs $1.10 of value per dollar going forward. Current CPI = 0.90. Going from 0.90 to 1.10 is a significant improvement: possible but challenging. CPI (A) shows where you ARE. EAC (B) forecasts where you're GOING. TCPI (D) answers what's NEEDED. On the exam, match the metric to the question asked."},
{q:"A PM compares contract types for an external firm. The scope is poorly defined and will evolve. The PM wants flexibility but needs cost protection. Which contract is MOST appropriate?",a:["Firm Fixed Price (FFP) to cap total project cost","Cost Plus Fixed Fee (CPFF) providing full cost reimbursement plus a set fee","Time and Materials (T&M) with a not-to-exceed clause for cost ceiling protection","Fixed Price Incentive Fee (FPIF) to motivate the vendor to control costs"],c:2,e:"With poorly defined, evolving scope: fixed-price (A, D) forces expensive renegotiations for changes. Pure cost-plus (B) has no cost ceiling. T&M with not-to-exceed (C) gives flexibility (pay actual time/materials as scope evolves) while capping exposure. On the exam: well-defined scope = fixed price (risk on seller). Undefined scope = cost-plus (risk on buyer). Evolving scope + cost protection = T&M with cap. The not-to-exceed clause is the key differentiator."},
// ===== DOMAIN 3: AGILE FRAMEWORKS (20 questions) =====
{q:"During sprint planning, the team says they can complete 30 story points based on velocity. The Product Owner insists on 45 points for a deadline. The Scrum Master should:",a:["Help the team voice their concerns, present velocity data, and facilitate a conversation about which stories within ~30 points best serve the deadline","Calculate average velocity and tell the PO that 40 is the maximum compromise","Support the PO since business deadlines take priority over team estimates","Let the team and PO negotiate without interference since this is their responsibility"],c:0,e:"Average velocity is 30. Committing to 45 is 50% above capacity: a recipe for failure. The SM should: (1) help the team voice concerns they're uncomfortable raising, (2) ground the discussion in data, (3) redirect from 'do more' to 'choose wisely': given ~30 points, which stories matter most? Supporting overcommitment (A) leads to sprint failure. A flat 'no' (B) is too blunt. Staying silent (D) ignores the SM's responsibility. On the exam, the SM facilitates with data. They don't dictate, stay silent, or enable overcommitment."},
{q:"A developer says during a retrospective: 'We keep getting pulled into production support mid-sprint.' The Scrum Master should:",a:["Reduce the team's velocity estimate to account for ongoing interruptions","Let the team decide how to handle it since they are self-organizing","Add a 20% capacity buffer to each sprint for unplanned work","Work with the PO and management to establish a dedicated support rotation so the full team isn't disrupted"],c:3,e:"This is an organizational impediment the team can't fix alone. A dedicated rotation (one person handles support on rotation) protects the rest of the team. Options A and C ACCOMMODATE the problem rather than SOLVE it. Option D sounds respectful of self-organization but ignores the SM's core duty: removing impediments the team can't remove themselves. The team can't unilaterally change how the org routes support requests. On the exam, the SM removes impediments first. Adjusting velocity is what you do AFTER you've tried to fix the root cause."},
{q:"A customer reports the delivered software meets all requirements but isn't intuitive. In agile, what most likely went wrong?",a:["The Definition of Done didn't include usability criteria, and the PO failed to involve real users in sprint reviews","The development team didn't follow technical specifications closely enough","The Scrum Master didn't enforce quality standards during the sprint","Nothing, since the product meets documented requirements and usability is subjective"],c:0,e:"Meeting requirements but missing usability means the requirements were incomplete. In agile, the PO should involve actual users in sprint reviews to catch usability gaps early. If the DoD doesn't include usability criteria, it's not being checked. Option D is a predictive mindset ('we built what was specified') that misses agile's principle of customer collaboration. Option B/C misdirect blame. On the exam, the DoD should include user acceptance criteria, and sprint reviews exist specifically to catch gaps like this."},
{q:"A Scrum team's velocity over 6 sprints: 34, 28, 31, 22, 35, 30. The PO asks how many points they can complete in the next 4 sprints. What is the BEST answer?",a:["140 points based on peak performance of 35 per sprint","Approximately 120 points based on average velocity of about 30 per sprint","Exactly 128 points based on the upward velocity trend","It's impossible to forecast because agile doesn't support long-term planning"],c:1,e:"Average = (34+28+31+22+35+30)/6 = 180/6 = 30. Forecast = 30 x 4 = 120 points. Using the peak (A) is optimistic and unreliable. Trending (C) assumes velocity always increases, which it doesn't. Option D is wrong: agile absolutely supports forecasting using velocity. This is exactly what velocity is for: empirical forecasting based on actual performance. On the exam, use AVERAGE velocity, not best case or trending."},
{q:"During sprint review, stakeholders love the increment, but the team knows significant technical debt could cause problems in future sprints. What should happen?",a:["Say nothing since stakeholders are happy and the increment works as expected","The Scrum Master should handle technical debt without involving the PO or stakeholders","Fix all technical debt immediately before delivering the increment to stakeholders","The team should transparently communicate the technical debt and its potential impact so the PO can prioritize it in the backlog"],c:3,e:"Transparency is a core Scrum value. Hiding technical debt creates false progress and eventually velocity collapse. The team should communicate debt to the PO, who makes the prioritization decision: address debt now (slower features) or accept risk (faster features, problems later). Silence (A) violates transparency. Immediate fixing (C) may not be practical. Excluding the PO (D) removes them from a decision that's theirs to make. On the exam, technical debt is a BUSINESS decision. The PO needs visibility to make informed trade-offs."},
{q:"In Kanban, work items pile up in the 'Code Review' column while other columns have capacity. What should the team do?",a:["Remove the WIP limit on Code Review to clear the backlog faster","Add more work to earlier columns to keep everyone productive and busy","Move items past Code Review since they're probably fine without it","Identify the bottleneck and consider having team members with available capacity help with code reviews"],c:3,e:"This is a bottleneck. Removing WIP limits (A) masks the problem and reduces quality. Adding upstream work (B) makes it worse. Skipping reviews (D) introduces quality risk. The correct approach: address the constraint by cross-training team members to help, pair on reviews, or examine why reviews take long. This is Theory of Constraints: identify the bottleneck, exploit it, subordinate everything else. On the exam, Kanban optimizes FLOW. Bottlenecks restrict flow. Fix the bottleneck, don't work around it."},
{q:"A team debates Scrum vs. Kanban for a support/maintenance project with unpredictable daily work intake. Items vary in size and priority. Which is more suitable?",a:["Kanban, because continuous flow handles variable intake without requiring fixed sprint timeboxes","Scrum, because all agile projects benefit from sprint structure and regular reviews","Scrum, because velocity tracking enables better long-term forecasting","Neither, because maintenance work should use a predictive approach"],c:0,e:"Kanban excels with unpredictable, variable work through continuous flow. New items are prioritized and pulled when capacity opens, without waiting for the next sprint. Scrum (A, C) works best when you can plan coherent 1-4 week batches, difficult with daily unpredictable intake. Maintenance is inherently adaptive (D is wrong). On the exam: predictable batches = Scrum. Continuous unpredictable flow = Kanban. Mix = hybrid."},
{q:"Three retrospectives in a row have produced improvement actions, but none have been implemented. The Scrum Master should:",a:["Cancel retrospectives since they aren't producing results","Assign each action to a specific person with a hard deadline","Report the team's failure to improve to management for intervention","Add improvement actions as sprint backlog items to ensure they receive time and attention"],c:3,e:"If improvements never get done, treat them as real work. Adding them to the sprint backlog gives them visibility and competes for time alongside feature work. Canceling retros (A) kills the inspect-and-adapt mechanism. Reporting to management (C) violates the safe space. Hard deadlines (D) are too directive for self-organizing teams. On the exam, continuous improvement requires actual commitment of time. Making items visible in the backlog creates accountability without being prescriptive."},
{q:"The PO receives an urgent feature request from the CEO mid-sprint. The team is on track to complete the sprint goal. What should the PO do?",a:["Add the feature to the current sprint since it's from the CEO","Cancel the sprint and start a new one incorporating the CEO's request","Acknowledge the request, add it to the backlog, and prioritize it for the next sprint","Tell the CEO to submit a formal change request through the project manager"],c:2,e:"Protecting sprint commitment is fundamental. Mid-sprint changes disrupt flow and undermine predictability. The PO should: acknowledge respectfully, capture in backlog, prioritize for NEXT sprint. Adding mid-sprint (A) violates sprint integrity regardless of who asks. Canceling (B) is extreme when the current sprint is on track. Redirecting to a formal CR process (D) is too bureaucratic for agile. On the exam, urgency from authority doesn't override sprint commitment. The PO protects the sprint."},
{q:"A team is considering changing from 2-week to 4-week sprints because they feel rushed. The Scrum Master should:",a:["Approve immediately since the self-organizing team should decide their sprint length","Explore why the team feels rushed before changing sprint length, since the root cause may be overcommitment or unclear requirements","Deny the request because 2-week sprints are the Scrum standard","Escalate to the PO since sprint length affects delivery frequency"],c:1,e:"Feeling rushed might signal overcommitment, poor refinement, unclear stories, technical debt, or interruptions. Changing sprint length treats the symptom. Self-organizing (A) doesn't mean any change is automatically right. Two-week sprints aren't mandatory (C). The PO doesn't decide sprint mechanics (D). The SM should facilitate root cause analysis first. On the exam, 'explore root cause before making changes' is almost always the right first step."},
{q:"Story points are used to estimate user stories. A senior developer says a story is '3 points.' A junior developer says the same story is '8 points.' What does this suggest about story points?",a:["The gap indicates the team needs to discuss the story to reach a shared understanding of scope, complexity, and unknowns","The estimates should be averaged to reach a compromise of 5.5 points","The senior developer is correct because they have more experience","Story points are unreliable because different people give different estimates"],c:0,e:"Estimation disagreement is a FEATURE of story points, not a bug. When estimates diverge significantly, it reveals that team members have different understandings of the work. The discussion that follows is where the real value is: maybe the junior sees complexity the senior hasn't considered, or the senior knows a shortcut the junior doesn't. Planning Poker deliberately surfaces these gaps. Averaging (B) skips the learning. Deferring to seniority (A) misses the junior's perspective. On the exam, estimation disagreements drive important conversations about scope and approach."},
{q:"In Scrum, only one person can cancel a sprint. Who has this authority and under what circumstance?",a:["The Scrum Master can cancel when the team is unable to complete the sprint goal","The sponsor can cancel when the project budget is exceeded","The Product Owner can cancel when the sprint goal becomes obsolete","The development team can cancel through a majority vote when work is blocked"],c:2,e:"Only the Product Owner has authority to cancel a sprint, and only when the sprint goal becomes obsolete (e.g., market shift, strategic pivot). Sprint cancellation is rare and disruptive. The SM doesn't have this authority (A). External stakeholders including the sponsor (B) don't control sprint mechanics. The team can't vote to cancel (D). On the exam, sprint cancellation = PO only, sprint goal obsolete only."},
// ===== DOMAIN 4: BUSINESS ANALYSIS (27 questions) =====
{q:"A BA is gathering requirements for a new inventory system. The warehouse manager says 'I need the system to be fast.' How should the BA handle this?",a:["Ask clarifying questions to produce a measurable requirement like 'inventory lookups must return results within 2 seconds'","Reject the requirement as too vague for the requirements document","Document it as stated: 'The system shall be fast' and let developers interpret it","Add it to the backlog as a user story and refine it during sprint planning"],c:0,e:"'Fast' is subjective and untestable. The BA probes: 'What does fast mean? What scenario is too slow currently? What response time is acceptable?' This yields measurable criteria: 'lookups within 2 seconds for 5,000 concurrent users.' Documenting vagueness (A) passes the problem downstream. Rejection (B) is too dismissive. Deferring to sprint planning (D) delays necessary analysis. On the exam, the BA always probes for specificity. Vague requirements should never be passed along as-is."},
{q:"A BA is conducting elicitation for a hospital system. Nurses describe their workflow differently from written procedures. What should the BA do?",a:["Trust the nurses since end users always know their workflow better than documentation","Trust the written procedures since they represent the organizational standard","Observe nurses working to validate what actually happens, then reconcile the gap between practice and documentation","Document both and let the sponsor decide which is correct"],c:2,e:"Neither source alone is reliable. Nurses might describe idealized workflows or skip steps they consider obvious. Procedures might be outdated or exist for compliance reasons nurses unknowingly violate. OBSERVATION gives ground truth. Then reconcile: maybe docs need updating, maybe nurses need retraining, maybe both. On the exam, when two sources conflict, gather additional evidence rather than trusting either source blindly."},
{q:"After an elicitation session produces 47 scattered requirements, many redundant and some conflicting, what should the BA do FIRST?",a:["Send the list to developers to begin work on the clearest items","Organize using an affinity diagram to group related items, then analyze for conflicts and gaps","Schedule another session to gather more requirements for completeness","Prioritize using MoSCoW and start with 'Must have' items"],c:1,e:"Before prioritizing (D) or starting work (A), you need to organize and understand what you have. Affinity diagrams group related items, revealing redundancies, conflicts, gaps, and themes. More elicitation (C) adds chaos without organizing existing input. The BA workflow: Elicit > Organize > Analyze > Prioritize > Validate. You can't skip from elicitation to prioritization. On the exam, organization and analysis precede prioritization."},
{q:"A requirements traceability matrix (RTM) is questioned by a team member as unnecessary overhead. What is the BEST justification for maintaining it?",a:["The PMO requires it as part of organizational standards for all projects","It serves as a checklist for the development team during coding","It provides the BA with a tool to track their personal work progress","It ensures every requirement traces from origin through design, development, and testing, preventing missed requirements or unjustified features"],c:3,e:"The RTM provides bidirectional traceability: forward (requirement > design > code > test) and backward (test > code > design > requirement). This ensures: no requirement is forgotten, no feature is built without justification (preventing gold plating), change impact is visible, and test coverage is verified. PMO compliance (A) is a reason but not the BEST. On the exam, traceability is about completeness and preventing scope issues, not just documentation compliance."},
{q:"Two senior stakeholders disagree on a critical requirement. One wants automated approval under $10K, the other insists all orders need manual approval for compliance. What should the BA do?",a:["Side with whichever stakeholder has more organizational authority","Document both positions, investigate the compliance requirement, and facilitate a follow-up session with evidence","Set the threshold at $5K as a compromise between the two positions","Escalate to the sponsor immediately for a binding decision"],c:1,e:"The BA facilitates, not decides. Before resolving, investigate WHY they disagree. Is there an actual compliance requirement? If so, it's a constraint, not a preference. The BA should: document positions, research compliance, bring evidence to a follow-up. Siding with authority (A) ignores compliance risk. Compromise (C) is arbitrary and may violate regulations. Immediate escalation (D) is premature. On the exam, the BA gathers evidence and facilitates. They don't decide, pick sides, or escalate prematurely."},
{q:"A product roadmap shows three releases over 12 months. What is its PRIMARY purpose?",a:["To serve as a detailed project schedule with specific delivery dates for each feature","To provide a high-level view of planned features and their delivery sequence so stakeholders understand the product's evolution","To replace the project management plan by consolidating all planning into one document","To lock in scope for all releases so no changes can be made going forward"],c:1,e:"A roadmap is a strategic communication tool showing WHAT will be delivered and in what ORDER, not exactly WHEN (that's the schedule). It helps stakeholders understand vision and evolution. It's not a detailed schedule (A), doesn't replace the project plan (C), and isn't a scope lock (D) since roadmaps adapt. On the exam: roadmap = strategic direction and sequencing. Schedule = specific dates and dependencies."},
{q:"The INVEST criteria evaluates user stories. A story reads: 'As a user, I want the system to be good.' Which criteria does this MOST clearly violate?",a:["Estimable and Testable","Valuable and Negotiable","Independent and Small","Independent and Valuable"],c:0,e:"INVEST: Independent, Negotiable, Valuable, Estimable, Small, Testable. 'Be good' is (1) not Estimable because 'good' is subjective and can't be sized, and (2) not Testable because no acceptance criteria can verify 'good.' A tester can't write a test for 'good.' On the exam, apply INVEST by asking: Can the team estimate this? Can a tester verify it? If no, the story needs refinement."},
{q:"Solution requirements in the RTM don't trace back to any business requirement. What does this indicate?",a:["Requirements may have been added without business justification, indicating scope creep or gold plating","The RTM has formatting errors needing correction","Business requirements were deleted by mistake during document updates","The solution is more comprehensive than needed, which adds value"],c:0,e:"Every solution requirement should trace to a business requirement justifying its existence. Orphan requirements indicate: someone added a feature without authorization (gold plating/scope creep) or a business requirement is missing. Option D is wrong because building more than requested wastes resources. Bidirectional traceability catches exactly this: unjustified work going forward and missed requirements going backward. On the exam, orphan requirements always signal a problem needing investigation."},
{q:"A company transitions from predictive to agile. The BA's role MOST significantly changes in which way?",a:["The BA creates more detailed documentation upfront to prepare each sprint with complete specs","The BA shifts from comprehensive upfront requirements to facilitating ongoing discovery through backlog refinement and iteration","The BA role is eliminated since the Product Owner handles all requirements work","The BA performs identical activities but uses agile terminology instead"],c:1,e:"In predictive, the BA creates comprehensive requirements docs during planning. In agile, requirements emerge iteratively through refinement, sprint reviews, and ongoing conversation. The BA doesn't disappear (C) but their work pattern changes from front-loaded documentation to continuous facilitation. More upfront docs (A) is the opposite of what happens. Same activities (D) underestimates the fundamental shift. On the exam, BA skills (elicitation, analysis, communication) remain valuable, but timing and format change significantly."},
{q:"A BA needs to gather requirements from 200 users across 5 countries with limited time and budget. Which elicitation technique is MOST appropriate?",a:["Individual interviews with key users in each country","Facilitated workshops conducted at each country location","Surveys and questionnaires distributed electronically","Focus groups with 5-10 representatives per country"],c:2,e:"200 users, 5 countries, limited budget: surveys scale efficiently, don't require travel, can be translated, and provide standardized data. Interviews (A) with 200 people would take months. Workshops (B) in 5 countries are expensive. Focus groups (D) are better but still require travel. On the exam, match technique to constraints: large numbers + geographic dispersion + limited budget = surveys. Small group + complex topics = workshops. Deep understanding = interviews. Process understanding = observation."},
{q:"Behavior-Driven Development (BDD) uses Given/When/Then. For a login feature, which is CORRECT?",a:["Given the user clicks login, When they enter credentials, Then access is granted","Given requirements exist, When developers read them, Then they build correctly","Given the system is working, When any action occurs, Then the system responds correctly","Given a registered user is on the login page, When they enter valid credentials and click submit, Then they are redirected to the dashboard within 2 seconds"],c:3,e:"BDD scenarios must be specific, testable, and describe observable behavior. Option B: Given (precondition: registered user, login page) > When (action: enter valid creds, click submit) > Then (outcome: redirect to dashboard within 2 sec). Option A reverses Given/When. Option C is untestably vague. Option D describes a process, not behavior. On the exam: Given = setup. When = user action. Then = expected observable, measurable outcome."},
{q:"During testing, the solution passes all test cases but doesn't align with the original business objectives from the business case. Test cases were written from solution requirements. What went wrong?",a:["Traceability broke: solution requirements drifted from business requirements during elaboration without anyone catching the misalignment","Testers wrote poor test cases that don't cover the right scenarios","Business objectives changed without anyone updating the documentation","The development team implemented the solution requirements incorrectly"],c:0,e:"If the solution passes tests but misses business objectives, the tests validate the wrong thing. The chain broke between business and solution requirements. This is exactly what RTM prevents: it ensures solution requirements trace to business requirements. Without active traceability, requirements drift through elaboration until the solution, while technically correct, no longer serves the original purpose. Tests passed (A is wrong). Implementation matched solution requirements (D is wrong). On the exam, traceability isn't overhead. It's the mechanism keeping the solution aligned with business value."},
{q:"A gap analysis identifies that manual data entry takes 4 hours daily. The future state requires automated ingestion in 15 minutes. What should the gap analysis OUTPUT?",a:["Identification of the capabilities, process changes, and technology needed to bridge the gap between current and future state","A recommendation to purchase specific automation software","A project charter authorizing the automation initiative","A cost-benefit analysis comparing manual versus automated approaches"],c:0,e:"Gap analysis identifies WHAT'S NEEDED to move between states, not HOW to get there (solution design) or WHETHER to proceed (cost-benefit). Output describes: capability gaps, process gaps, technology gaps, people gaps. Recommending specific software (A) is premature. Charter (C) and cost-benefit (D) come after gap analysis informs decisions. On the exam: gap analysis = what's missing between states. Solution recommendation is a separate process."},
{q:"Users report the new system works correctly but hasn't improved productivity as the business case promised. What should the BA do?",a:["Close the project since the system meets all technical requirements","Investigate why expected value isn't being realized by comparing actual performance against business case metrics and identifying barriers","Recommend reverting to the old system immediately","Document as a lesson learned and move to the next project"],c:1,e:"Meeting technical requirements but failing to deliver value means something broke between requirements and outcomes. Investigate: training issue? Process change failed? Business case assumptions wrong? User resistance? Closing (A) ignores the business purpose. Reverting (C) is extreme. Moving on (D) wastes the investment. On the exam, solution evaluation isn't just 'does it work?' It's 'does it deliver promised value?' The BA's job extends to value realization."},
{q:"Three stakeholders of equal authority provide conflicting priorities for the next release. The BA should:",a:["Escalate to the sponsor to make the priority decision since peers can't resolve it themselves","Recommend the customer-facing feature since those typically generate the highest business value","Facilitate a prioritization session using objective criteria like business value, cost of delay, and strategic alignment","Build all three features simultaneously by dividing the team into sub-groups"],c:2,e:"When peers disagree, the BA FACILITATES using objective criteria to depersonalize the decision. Instead of 'whose department matters more,' it becomes 'which has highest value and cost of delay?' Escalation (A) creates political problems and abdicates facilitation responsibility. Assumptions about value (B) lack evidence. Splitting teams (D) ignores resource constraints and reduces velocity. On the exam, the BA helps stakeholders decide using structured analysis. They don't decide for them."},
{q:"The Delphi technique is useful for requirements gathering because:",a:["It's the fastest way to collect requirements from large groups","It requires only one expert to provide all necessary requirements","It eliminates the need for follow-up sessions after initial input","It uses anonymous rounds of expert input, preventing dominant personalities from influencing the group consensus"],c:3,e:"Delphi's key advantage is anonymity. Experts provide input independently, results are aggregated and shared, then experts revise their input over multiple rounds. This prevents groupthink and political pressure. It's not fast (A) since it requires multiple rounds. Follow-up rounds are inherent (C). Multiple experts are essential (D). On the exam, Delphi = anonymous expert consensus. Use it when political dynamics or dominant personalities would skew group results."},
{q:"A power/interest grid classifies stakeholders. A stakeholder with HIGH power and LOW interest should be managed by:",a:["Keeping them closely managed with frequent detailed updates","Keeping them satisfied with periodic updates but not overwhelming them with detail","Monitoring them with minimal effort since they're not interested","Keeping them informed through regular communication channels"],c:1,e:"High power + low interest = Keep Satisfied. They CAN impact your project but currently AREN'T engaged. Don't bore them with detail (they'll disengage further), but don't ignore them (they could become a blocker). Periodic, relevant updates maintain the relationship. High power + high interest = Manage Closely. Low power + high interest = Keep Informed. Low power + low interest = Monitor. On the exam, know all four quadrants and the management strategy for each."},
// ===== CROSS-DOMAIN APPLICATION/JUDGMENT (6 questions) =====
{q:"A PM manages a project 75% complete when the sponsor announces a 15% budget cut. What should the PM do FIRST?",a:["Lay off team members immediately to reduce costs","Continue as planned and hope remaining work comes in under estimate","Halt all work until the budget situation is fully resolved","Perform impact analysis to determine what scope can still be delivered within the reduced budget, then present options to the sponsor"],c:3,e:"Before acting, understand the impact. What can you deliver with 85% of budget? What must be cut? Present the sponsor with options: reduce scope, extend timeline, reduce quality (risky), or accept higher risk. Options A, B, D are reactive without analysis. On the exam, when constraints change, ALWAYS: impact analysis first > present options to stakeholders > get a decision > execute. Never act without understanding consequences."},
{q:"A team member finds a security vulnerability that could expose customer data. Fixing it delays launch by 3 weeks. The sponsor says the date can't move. What should the PM do?",a:["Launch on time and fix the vulnerability in a post-launch patch","Document the vulnerability, assess legal and financial exposure, and escalate to the sponsor with a clear recommendation to delay","Let the team member decide how to handle it since they discovered it","Fix it quietly without informing the sponsor about the schedule impact"],c:1,e:"Security vulnerabilities exposing customer data carry legal liability, reputational risk, and financial penalties far exceeding 3 weeks of delay. The PM must document, assess full impact, and present to the sponsor who may not realize the consequences. Launching with a known vulnerability (A) could be negligent. Hiding delays (D) is dishonest. Delegating to a team member (C) abdicates responsibility. On the exam, ethical and legal obligations always override schedule pressure."},
{q:"A PM takes over a project midway. Documentation is incomplete, the team is disengaged, and stakeholders are frustrated. What should the PM prioritize FIRST?",a:["Review all documentation and create a complete project management plan before taking any action","Meet individually with key stakeholders and team members to understand the current situation and concerns","Call a team meeting to establish new ground rules and set clear expectations","Review budget and schedule to determine if the project is still financially viable"],c:1,e:"When taking over a troubled project, understand the HUMAN landscape before the documentation landscape. Individual meetings let people speak candidly about what's wrong. You'll learn the real issues: PM incompetence? Scope disputes? Resource gaps? Once you understand from multiple perspectives, you can prioritize fixes. Group meetings (C) suppress honest feedback. Documentation review (A) is important but doesn't address the people problem. Budget review (D) is important but secondary to understanding the full picture."},
{q:"A change control board approves a 10% scope increase. The PM updates the scope baseline but NOT the schedule or cost baselines. Two months later, the project appears behind schedule and over budget. What went wrong?",a:["The CCB shouldn't have approved such a large change without more analysis","The team is underperforming and needs additional oversight to meet targets","The PM failed to perform integrated change control by not updating ALL affected baselines when scope changed","The original estimates were optimistic and the change merely exposed the real timeline"],c:2,e:"Integrated change control means updating impacts across ALL knowledge areas. A 10% scope increase affects schedule (more work = more time) and cost (more work = more money). By only updating scope, the PM created a measurement mismatch: performance is judged against targets that don't reflect approved scope. It LOOKS like failure but it's a measurement error. On the exam, 'integrated' means integrated. Every scope change triggers: does this affect schedule? Cost? Quality? Risk? Resources? Update everything."},
{q:"A PM notices 23 scope changes approved in 2 months, all through proper change control. What should concern the PM?",a:["The high volume suggests the original scope was poorly defined or stakeholder requirements weren't adequately captured during planning","The change control board is being too permissive and should reject more changes","Nothing, since all changes followed the proper change control process","23 changes in 2 months is normal for any active project of this size"],c:0,e:"Following process is necessary but not sufficient. 23 approved changes in 2 months is a red flag about the UPSTREAM process. Either: requirements gathering was incomplete, stakeholder needs weren't understood, scope was too vague, or the environment is genuinely volatile. The PM should investigate root cause. A more restrictive board (B) doesn't fix why changes are being requested. On the exam, don't assume following process means everything is fine. High change volume signals a planning or elicitation problem."},
{q:"A project team using a hybrid approach has predictive infrastructure phases and agile software sprints. Infrastructure falls 2 weeks behind, which will delay software work. What should the PM do?",a:["Switch the entire project to agile for more flexibility","Tell the software team to wait until infrastructure catches up","Remove infrastructure from project scope to eliminate the dependency","Crash infrastructure by adding resources, and adjust the software backlog to prioritize items that don't depend on infrastructure"],c:3,e:"Address both streams with appropriate techniques: crash the predictive work (add resources to infrastructure) while keeping the agile team productive on independent items. Switching to agile (A) doesn't solve infrastructure delay. Waiting (B) wastes capacity. Removing infrastructure (D) eliminates a necessary component. On the exam, hybrid questions test whether you apply the right technique to the right work type: predictive techniques for predictive work, agile techniques for agile work."},
];

function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}

export default function CAPMQuiz(){
  const[questions,setQuestions]=useState([]);
  const[idx,setIdx]=useState(0);
  const[selected,setSelected]=useState(null);
  const[showResult,setShowResult]=useState(false);
  const[score,setScore]=useState(0);
  const[total,setTotal]=useState(0);
  const[sessionOver,setSessionOver]=useState(false);
  const[reviewMode,setReviewMode]=useState(false);
  const[missed,setMissed]=useState([]);
  const[reviewIdx,setReviewIdx]=useState(0);
  const containerRef=useRef(null);

  const startQuiz=useCallback(()=>{
    setQuestions(shuffle(QUESTIONS));setIdx(0);setSelected(null);setShowResult(false);
    setScore(0);setTotal(0);setSessionOver(false);setReviewMode(false);setMissed([]);setReviewIdx(0);
  },[]);

  useEffect(()=>{startQuiz();},[startQuiz]);

  const current=reviewMode?missed[reviewIdx]:questions[idx];
  const handleSelect=(i)=>{
    if(showResult)return;setSelected(i);setShowResult(true);
    if(!reviewMode){setTotal(t=>t+1);if(i===current.c)setScore(s=>s+1);else setMissed(m=>[...m,{...current}]);}
  };
  const handleNext=()=>{
    if(reviewMode){if(reviewIdx+1>=missed.length){setReviewMode(false);setSessionOver(true);}else setReviewIdx(r=>r+1);}
    else{if(idx+1>=questions.length)setSessionOver(true);else setIdx(i=>i+1);}
    setSelected(null);setShowResult(false);if(containerRef.current)containerRef.current.scrollTop=0;
  };

  const pct=total>0?Math.round((score/total)*100):0;
  const qNum=reviewMode?reviewIdx+1:idx+1;
  const qTotal=reviewMode?missed.length:questions.length;
  if(!current&&!sessionOver)return null;

  return(
    <div ref={containerRef} style={{fontFamily:"'IBM Plex Mono','SF Mono',monospace",background:"var(--bg)",color:"var(--fg)",minHeight:"100vh",padding:"24px 16px",boxSizing:"border-box"}}>
      <style>{`
        :root{--bg:#0c0c12;--fg:#e4e2de;--card:#15151d;--border:#28283a;--accent:#6ee7b7;--accent-dim:#1a3a2a;--wrong:#f87171;--wrong-dim:#3a1a1a;--muted:#6b7280;--explain-bg:#1a1a28}
        @media(prefers-color-scheme:light){:root{--bg:#f5f5f0;--fg:#1a1a2e;--card:#fff;--border:#d1d5db;--accent:#059669;--accent-dim:#d1fae5;--wrong:#dc2626;--wrong-dim:#fee2e2;--muted:#6b7280;--explain-bg:#f9f9f6}}
        *{box-sizing:border-box;margin:0;padding:0}
      `}</style>

      <div style={{maxWidth:720,margin:"0 auto 28px",display:"flex",justifyContent:"space-between",alignItems:"baseline",borderBottom:"1px solid var(--border)",paddingBottom:14}}>
        <div>
          <div style={{fontSize:10,letterSpacing:3,color:"var(--muted)",textTransform:"uppercase",marginBottom:3}}>{reviewMode?"Reviewing Missed":"CAPM Exam Prep"}</div>
          <div style={{fontSize:18,fontWeight:600}}>{QUESTIONS.length} Questions</div>
        </div>
        <div style={{textAlign:"right"}}>
          <div style={{fontSize:24,fontWeight:600,color:total===0?"var(--muted)":pct>=75?"var(--accent)":pct>=55?"#fbbf24":"var(--wrong)"}}>{total>0?`${pct}%`:"---"}</div>
          <div style={{fontSize:10,color:"var(--muted)",letterSpacing:1}}>{score}/{total}</div>
        </div>
      </div>

      {sessionOver?(
        <div style={{maxWidth:720,margin:"0 auto",padding:36,background:"var(--card)",border:"1px solid var(--border)",borderRadius:8,textAlign:"center"}}>
          <div style={{fontSize:40,fontWeight:600,marginBottom:6,color:pct>=75?"var(--accent)":pct>=55?"#fbbf24":"var(--wrong)"}}>{pct}%</div>
          <div style={{fontSize:12,color:"var(--muted)",marginBottom:6}}>{score} of {total}</div>
          <div style={{fontSize:12,marginBottom:28,color:"var(--muted)",lineHeight:1.6}}>
            {pct>=80?"Strong. Keep drilling to lock it in.":pct>=65?"Passing range. Focus on the explanations for misses.":pct>=50?"Getting there. Re-read explanations carefully.":"Keep working. The explanations are where the learning happens."}
          </div>
          <div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap"}}>
            {missed.length>0&&!reviewMode&&(
              <button onClick={()=>{setReviewMode(true);setReviewIdx(0);setSessionOver(false);setSelected(null);setShowResult(false);}} style={{padding:"11px 22px",background:"transparent",border:"1px solid var(--border)",color:"var(--fg)",borderRadius:6,cursor:"pointer",fontSize:11,fontFamily:"inherit"}}>
                Review {missed.length} missed
              </button>
            )}
            <button onClick={startQuiz} style={{padding:"11px 22px",background:"var(--accent)",color:"#0c0c12",border:"none",borderRadius:6,cursor:"pointer",fontSize:11,fontWeight:600,fontFamily:"inherit"}}>New session</button>
          </div>
        </div>
      ):(
        <div style={{maxWidth:720,margin:"0 auto"}}>
          <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}>
            <div style={{fontSize:10,color:"var(--muted)",letterSpacing:1}}>{qNum}/{qTotal}</div>
            <div style={{flex:1,height:2,background:"var(--border)",borderRadius:1}}>
              <div style={{height:2,background:"var(--accent)",borderRadius:1,width:`${(qNum/qTotal)*100}%`,transition:"width 0.3s"}}/>
            </div>
          </div>

          <div style={{background:"var(--card)",border:"1px solid var(--border)",borderRadius:8,padding:"22px 18px",marginBottom:12}}>
            <div style={{fontSize:13,lineHeight:1.85,fontWeight:500}}>{current.q}</div>
          </div>

          <div style={{display:"flex",flexDirection:"column",gap:5,marginBottom:14}}>
            {current.a.map((opt,i)=>{
              const isC=i===current.c,isS=i===selected;
              let bg="var(--card)",bc="var(--border)";
              if(showResult){if(isC){bg="var(--accent-dim)";bc="var(--accent)";}else if(isS){bg="var(--wrong-dim)";bc="var(--wrong)";}}
              return(
                <button key={i} onClick={()=>handleSelect(i)} disabled={showResult} style={{
                  display:"flex",alignItems:"flex-start",gap:10,padding:"11px 14px",
                  background:bg,border:`1px solid ${bc}`,borderRadius:6,color:"var(--fg)",
                  cursor:showResult?"default":"pointer",fontSize:12.5,lineHeight:1.75,
                  fontFamily:"inherit",textAlign:"left",transition:"all 0.15s",
                  opacity:showResult&&!isC&&!isS?0.3:1,
                }}>
                  <span style={{flexShrink:0,width:20,height:20,borderRadius:3,border:`1px solid ${bc}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:600,marginTop:2,color:showResult&&isC?"var(--accent)":showResult&&isS&&!isC?"var(--wrong)":"var(--muted)"}}>{String.fromCharCode(65+i)}</span>
                  <span>{opt}</span>
                </button>
              );
            })}
          </div>

          {showResult&&(
            <div style={{background:"var(--explain-bg)",border:`1px solid ${selected===current.c?"var(--accent)":"var(--wrong)"}`,borderRadius:8,padding:"16px 18px",marginBottom:14}}>
              <div style={{fontSize:10,fontWeight:600,letterSpacing:2,textTransform:"uppercase",marginBottom:10,color:selected===current.c?"var(--accent)":"var(--wrong)"}}>{selected===current.c?"Correct":"Incorrect"}</div>
              <div style={{fontSize:12.5,lineHeight:1.9,color:"var(--fg)",opacity:0.9}}>{current.e}</div>
            </div>
          )}

          {showResult&&(
            <button onClick={handleNext} style={{width:"100%",padding:"12px",background:"var(--accent)",color:"#0c0c12",border:"none",borderRadius:6,cursor:"pointer",fontSize:12,fontWeight:600,fontFamily:"inherit"}}>
              {(reviewMode&&reviewIdx+1>=missed.length)||(!reviewMode&&idx+1>=questions.length)?"See Results":"Next"}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
